"""empty message

Revision ID: 014ba9cd9efd
Revises: cffdc36a0a84
Create Date: 2025-11-04 11:48:25.579918

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "014ba9cd9efd"
down_revision = "cffdc36a0a84"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("knowledge_base", schema=None) as batch_op:
        batch_op.alter_column("topic", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("title", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "knowledge_base_document", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("is_visible", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("status", existing_type=sa.BOOLEAN(), nullable=False)

    with op.batch_alter_table("log_user", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "type_of_action", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "time_of_action", existing_type=postgresql.TIMESTAMP(), nullable=False
        )

    with op.batch_alter_table("mis_tracker", schema=None) as batch_op:
        batch_op.alter_column("txt_period", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "txt_mis_type", existing_type=sa.VARCHAR(), nullable=False
        )

    with op.batch_alter_table("outstanding_expenses", schema=None) as batch_op:
        batch_op.alter_column(
            "str_regional_office_code", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "str_operating_office_code", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "str_party_type", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "str_party_id", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "str_party_name", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "float_gross_amount",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "float_net_amount",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "str_nature_of_payment", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("str_narration", existing_type=sa.TEXT(), nullable=False)

    with op.batch_alter_table("ticket_remarks", schema=None) as batch_op:
        batch_op.alter_column("ticket_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("remarks", existing_type=sa.TEXT(), nullable=False)
        batch_op.create_foreign_key(
            batch_op.f("fk_ticket_remarks_ticket_id_tickets"),
            "tickets",
            ["ticket_id"],
            ["id"],
        )

    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.alter_column(
            "regional_office_code", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("office_code", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "ticket_number", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "contact_person", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "contact_mobile_number", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "contact_email_address", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("status", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("department", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_by", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("created_on", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("updated_by", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("updated_on", sa.DateTime(), nullable=True))
        batch_op.alter_column("ro_code", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("oo_code", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("username", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("password", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("user_type", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "reset_password", existing_type=sa.BOOLEAN(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "reset_password", existing_type=sa.BOOLEAN(), nullable=True
        )
        batch_op.alter_column("user_type", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("password", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("username", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("oo_code", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("ro_code", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.drop_column("updated_on")
        batch_op.drop_column("updated_by")
        batch_op.drop_column("created_on")
        batch_op.drop_column("created_by")

    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.alter_column("department", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("status", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "contact_email_address", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "contact_mobile_number", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "contact_person", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "ticket_number", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("office_code", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "regional_office_code", existing_type=sa.VARCHAR(), nullable=True
        )

    with op.batch_alter_table("ticket_remarks", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_ticket_remarks_ticket_id_tickets"), type_="foreignkey"
        )
        batch_op.alter_column("remarks", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("ticket_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("outstanding_expenses", schema=None) as batch_op:
        batch_op.alter_column("str_narration", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column(
            "str_nature_of_payment", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "float_net_amount",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "float_gross_amount",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "str_party_name", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("str_party_id", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "str_party_type", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "str_operating_office_code", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "str_regional_office_code", existing_type=sa.VARCHAR(), nullable=True
        )

    with op.batch_alter_table("mis_tracker", schema=None) as batch_op:
        batch_op.alter_column("txt_mis_type", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("txt_period", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("log_user", schema=None) as batch_op:
        batch_op.alter_column(
            "time_of_action", existing_type=postgresql.TIMESTAMP(), nullable=True
        )
        batch_op.alter_column(
            "type_of_action", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("user_id", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("knowledge_base", schema=None) as batch_op:
        batch_op.alter_column("status", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("is_visible", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column(
            "knowledge_base_document", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("title", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("topic", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###
