"""Work allocation: Create models

Revision ID: 045313e07f72
Revises: c75401a91e5f
Create Date: 2026-04-25 14:20:22.249929

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "045313e07f72"
down_revision = "c75401a91e5f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "work_allocation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bank_name", sa.String(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("officer_name", sa.String(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_allocation")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("work_allocation")
    # ### end Alembic commands ###
