"""empty message

Revision ID: 0c241f922a45
Revises: 1ec4291b5cef
Create Date: 2025-12-02 18:12:07.274839

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0c241f922a45"
down_revision = "1ec4291b5cef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fund_outflow_label",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("outflow_label", sa.String(), nullable=False),
        sa.Column("date_created_date", sa.DateTime(), nullable=True),
        sa.Column("date_updated_date", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fund_outflow_label")),
        sa.UniqueConstraint(
            "outflow_label", name=op.f("uq_fund_outflow_label_outflow_label")
        ),
    )
    with op.batch_alter_table("bank_recon_account_details", schema=None) as batch_op:
        batch_op.alter_column(
            "str_name_of_bank", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "str_brs_type", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "str_bank_account_number", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "str_ifsc_code", existing_type=sa.VARCHAR(), nullable=False
        )

    with op.batch_alter_table("bank_recon_excess_credit", schema=None) as batch_op:
        batch_op.alter_column(
            "brs_month_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "date_of_collection", existing_type=sa.DATE(), nullable=False
        )

    with op.batch_alter_table("bank_recon_short_credit", schema=None) as batch_op:
        batch_op.alter_column(
            "brs_month_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "instrument_amount",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "date_of_collection", existing_type=sa.DATE(), nullable=False
        )

    with op.batch_alter_table("brs", schema=None) as batch_op:
        batch_op.alter_column(
            "uiic_regional_code", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "uiic_office_code", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "financial_year", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("month", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table("brs_month", schema=None) as batch_op:
        batch_op.alter_column("brs_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("brs_type", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "int_opening_balance",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "int_opening_on_hand",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "int_transactions",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "int_cancellations",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "int_fund_transfer",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "int_bank_charges",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "int_closing_on_hand",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "int_closing_balance",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "int_deposited_not_credited",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "int_short_credited",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "int_excess_credited",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "int_balance_as_per_bank",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column("prepared_by", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "prepared_by_employee_number", existing_type=sa.VARCHAR(), nullable=False
        )

    with op.batch_alter_table("delete_entries", schema=None) as batch_op:
        batch_op.alter_column("txt_month", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "bool_enable_delete", existing_type=sa.BOOLEAN(), nullable=False
        )

    with op.batch_alter_table("outstanding", schema=None) as batch_op:
        batch_op.alter_column(
            "brs_month_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "instrument_amount",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )

    with op.batch_alter_table("recon_entries", schema=None) as batch_op:
        batch_op.alter_column("str_period", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "str_regional_office_code", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("txt_remarks", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column(
            "str_debit_credit", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "amount_recon",
            existing_type=sa.NUMERIC(precision=20, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "str_head_office_status", existing_type=sa.VARCHAR(), nullable=False
        )

    with op.batch_alter_table("recon_summary", schema=None) as batch_op:
        batch_op.alter_column("str_period", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "str_regional_office_code", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "input_ro_balance_dr_cr", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "input_float_ro_balance",
            existing_type=sa.NUMERIC(precision=20, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "input_ho_balance_dr_cr", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "input_float_ho_balance",
            existing_type=sa.NUMERIC(precision=20, scale=2),
            nullable=False,
        )
        batch_op.drop_column("float_ho_balance")

    with op.batch_alter_table("recon_update_balance", schema=None) as batch_op:
        batch_op.alter_column("str_period", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "str_regional_office_code", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "ro_balance",
            existing_type=sa.NUMERIC(precision=20, scale=2),
            nullable=False,
        )
        batch_op.alter_column("ro_dr_cr", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "ho_balance",
            existing_type=sa.NUMERIC(precision=20, scale=2),
            nullable=False,
        )
        batch_op.alter_column("ho_dr_cr", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recon_update_balance", schema=None) as batch_op:
        batch_op.alter_column("ho_dr_cr", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "ho_balance", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=True
        )
        batch_op.alter_column("ro_dr_cr", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "ro_balance", existing_type=sa.NUMERIC(precision=20, scale=2), nullable=True
        )
        batch_op.alter_column(
            "str_regional_office_code", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("str_period", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("recon_summary", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "float_ho_balance",
                sa.NUMERIC(precision=20, scale=2),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.alter_column(
            "input_float_ho_balance",
            existing_type=sa.NUMERIC(precision=20, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "input_ho_balance_dr_cr", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "input_float_ro_balance",
            existing_type=sa.NUMERIC(precision=20, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "input_ro_balance_dr_cr", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "str_regional_office_code", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("str_period", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("recon_entries", schema=None) as batch_op:
        batch_op.alter_column(
            "str_head_office_status", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "amount_recon",
            existing_type=sa.NUMERIC(precision=20, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "str_debit_credit", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("txt_remarks", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column(
            "str_regional_office_code", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("str_period", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("outstanding", schema=None) as batch_op:
        batch_op.alter_column(
            "instrument_amount",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column("brs_month_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("delete_entries", schema=None) as batch_op:
        batch_op.alter_column(
            "bool_enable_delete", existing_type=sa.BOOLEAN(), nullable=True
        )
        batch_op.alter_column("txt_month", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("brs_month", schema=None) as batch_op:
        batch_op.alter_column(
            "prepared_by_employee_number", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("prepared_by", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "int_balance_as_per_bank",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "int_excess_credited",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "int_short_credited",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "int_deposited_not_credited",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "int_closing_balance",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "int_closing_on_hand",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "int_bank_charges",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "int_fund_transfer",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "int_cancellations",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "int_transactions",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "int_opening_on_hand",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "int_opening_balance",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column("brs_type", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("brs_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("brs", schema=None) as batch_op:
        batch_op.alter_column("month", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "financial_year", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "uiic_office_code", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "uiic_regional_code", existing_type=sa.VARCHAR(), nullable=True
        )

    with op.batch_alter_table("bank_recon_short_credit", schema=None) as batch_op:
        batch_op.alter_column(
            "date_of_collection", existing_type=sa.DATE(), nullable=True
        )
        batch_op.alter_column(
            "instrument_amount",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column("brs_month_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("bank_recon_excess_credit", schema=None) as batch_op:
        batch_op.alter_column(
            "date_of_collection", existing_type=sa.DATE(), nullable=True
        )
        batch_op.alter_column("brs_month_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("bank_recon_account_details", schema=None) as batch_op:
        batch_op.alter_column(
            "str_ifsc_code", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "str_bank_account_number", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("str_brs_type", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "str_name_of_bank", existing_type=sa.VARCHAR(), nullable=True
        )

    op.drop_table("fund_outflow_label")
    # ### end Alembic commands ###
