"""empty message

Revision ID: 0c8ceb77480b
Revises: 970b0de246bb
Create Date: 2024-12-20 12:50:16.655855

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0c8ceb77480b"
down_revision = "970b0de246bb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lien",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ro_code", sa.String(), nullable=True),
        sa.Column("ro_name", sa.String(), nullable=True),
        sa.Column("court_name", sa.String(), nullable=True),
        sa.Column("case_number", sa.String(), nullable=True),
        sa.Column("petitioner_name", sa.String(), nullable=True),
        sa.Column("date_of_order", sa.Date(), nullable=True),
        sa.Column("lien_amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("dd_amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("action_taken_by_banker", sa.Text(), nullable=True),
        sa.Column("bank_name", sa.String(), nullable=True),
        sa.Column("account_number", sa.String(), nullable=True),
        sa.Column("ro_remarks", sa.Text(), nullable=True),
        sa.Column("lien_status", sa.String(), nullable=True),
        sa.Column("court_order_lien", sa.String(), nullable=True),
        sa.Column("court_order_dd", sa.String(), nullable=True),
        sa.Column("court_order_lien_reversal", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lien")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lien")
    # ### end Alembic commands ###
