"""empty message

Revision ID: 0cba317334d7
Revises: dc60b74e8fe8
Create Date: 2025-09-23 11:45:33.979332

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0cba317334d7"
down_revision = "dc60b74e8fe8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("brs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("dqr_bank", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("dqr_brs_id", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("brs", schema=None) as batch_op:
        batch_op.drop_column("dqr_brs_id")
        batch_op.drop_column("dqr_bank")

    # ### end Alembic commands ###
