"""empty message

Revision ID: 10fd113afe4a
Revises: c3d62f8d6013
Create Date: 2024-07-15 12:41:35.850528

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "10fd113afe4a"
down_revision = "c3d62f8d6013"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("coinsurance", schema=None) as batch_op:
        batch_op.add_column(sa.Column("str_period", sa.String(), nullable=True))

    with op.batch_alter_table("coinsurance_cash_call", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("str_leader_follower", sa.String(), nullable=True)
        )

    with op.batch_alter_table("coinsurance_log", schema=None) as batch_op:
        batch_op.add_column(sa.Column("str_period", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("coinsurance_log", schema=None) as batch_op:
        batch_op.drop_column("str_period")

    with op.batch_alter_table("coinsurance_cash_call", schema=None) as batch_op:
        batch_op.drop_column("str_leader_follower")

    with op.batch_alter_table("coinsurance", schema=None) as batch_op:
        batch_op.drop_column("str_period")

    # ### end Alembic commands ###
