"""Fund flow: Initial commit

Revision ID: 172c94d6901a
Revises: bee3031e55ac
Create Date: 2026-06-11 20:52:04.064017

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "172c94d6901a"
down_revision = "bee3031e55ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fund_flow_bank_charges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bank_name", sa.String(), nullable=False),
        sa.Column("month", sa.String(), nullable=False),
        sa.Column("fixed_charges", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("variable_charges", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fund_flow_bank_charges")),
    )
    op.create_table(
        "fund_inflow_summary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type_of_collection", sa.String(), nullable=False),
        sa.Column("bank_vendor_name", sa.String(), nullable=False),
        sa.Column("mode_of_collection", sa.String(), nullable=False),
        sa.Column("month", sa.String(), nullable=False),
        sa.Column("number_of_transactions", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fund_inflow_summary")),
    )
    op.create_table(
        "fund_outflow_summary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bank_name", sa.String(), nullable=False),
        sa.Column("mode_of_payment", sa.String(), nullable=False),
        sa.Column("month", sa.String(), nullable=False),
        sa.Column("number_of_transactions", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fund_outflow_summary")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fund_outflow_summary")
    op.drop_table("fund_inflow_summary")
    op.drop_table("fund_flow_bank_charges")
    # ### end Alembic commands ###
