"""empty message

Revision ID: 18070708dcf2
Revises: 612021ae9b0e
Create Date: 2024-06-18 12:42:13.445534

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "18070708dcf2"
down_revision = "612021ae9b0e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fund_journal_voucher_flag_sheet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("txt_description", sa.String(), nullable=True),
        sa.Column("txt_flag", sa.String(), nullable=True),
        sa.Column("txt_gl_code", sa.String(), nullable=True),
        sa.Column("txt_sl_code", sa.String(), nullable=True),
        sa.Column("current_status", sa.String(), nullable=True),
        sa.Column("date_created_date", sa.DateTime(), nullable=True),
        sa.Column("date_updated_date", sa.DateTime(), nullable=True),
        sa.Column("date_deleted_date", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fund_journal_voucher_flag_sheet")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fund_journal_voucher_flag_sheet")
    # ### end Alembic commands ###
