"""Add status column in DD model

Revision ID: 1d77e21c2f6f
Revises: 7332e372079b
Create Date: 2026-02-11 12:08:49.275636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d77e21c2f6f'
down_revision = '7332e372079b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coinsurance_version', schema=None) as batch_op:
        batch_op.create_index('ix_coinsurance_version_pk_transaction_id', ['id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_coinsurance_version_pk_validity', ['id', 'transaction_id', 'end_transaction_id'], unique=False)

    with op.batch_alter_table('direct_debit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('DD debited', 'DD reversed', name='status', native_enum=False), nullable=False))
        batch_op.add_column(sa.Column('dd_reversal_date', sa.Date(), nullable=True))

    with op.batch_alter_table('lien_version', schema=None) as batch_op:
        batch_op.create_index('ix_lien_version_pk_transaction_id', ['id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_lien_version_pk_validity', ['id', 'transaction_id', 'end_transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lien_version', schema=None) as batch_op:
        batch_op.drop_index('ix_lien_version_pk_validity')
        batch_op.drop_index('ix_lien_version_pk_transaction_id')

    with op.batch_alter_table('direct_debit', schema=None) as batch_op:
        batch_op.drop_column('dd_reversal_date')
        batch_op.drop_column('status')

    with op.batch_alter_table('coinsurance_version', schema=None) as batch_op:
        batch_op.drop_index('ix_coinsurance_version_pk_validity')
        batch_op.drop_index('ix_coinsurance_version_pk_transaction_id')

    # ### end Alembic commands ###
