"""empty message

Revision ID: 1e0fcdb3e358
Revises: a0cde34b0fad
Create Date: 2024-07-08 11:42:03.943740

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1e0fcdb3e358"
down_revision = "a0cde34b0fad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_recon_account_details",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("str_name_of_bank", sa.String(), nullable=True),
        sa.Column("str_brs_type", sa.String(), nullable=True),
        sa.Column("str_bank_account_number", sa.String(), nullable=True),
        sa.Column("str_ifsc_code", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_recon_account_details")),
    )
    with op.batch_alter_table("coinsurance_balances", schema=None) as batch_op:
        batch_op.add_column(sa.Column("str_zone", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("str_regional_office_code", sa.String(), nullable=True)
        )
        batch_op.add_column(sa.Column("created_by", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("created_on", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("updated_by", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("updated_on", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("deleted_by", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("deleted_on", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("coinsurance_balances", schema=None) as batch_op:
        batch_op.drop_column("deleted_on")
        batch_op.drop_column("deleted_by")
        batch_op.drop_column("updated_on")
        batch_op.drop_column("updated_by")
        batch_op.drop_column("created_on")
        batch_op.drop_column("created_by")
        batch_op.drop_column("str_regional_office_code")
        batch_op.drop_column("str_zone")

    op.drop_table("bank_recon_account_details")
    # ### end Alembic commands ###
