"""empty message

Revision ID: 1ec4291b5cef
Revises: d6b0ac20e80b
Create Date: 2025-11-24 19:04:56.239546

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1ec4291b5cef"
down_revision = "d6b0ac20e80b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coinsurance_version",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column(
            "uiic_regional_code", sa.String(), autoincrement=False, nullable=True
        ),
        sa.Column("uiic_office_code", sa.String(), autoincrement=False, nullable=True),
        sa.Column(
            "follower_company_name", sa.String(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "follower_office_code", sa.String(), autoincrement=False, nullable=True
        ),
        sa.Column("str_period", sa.String(), autoincrement=False, nullable=True),
        sa.Column(
            "type_of_transaction", sa.String(), autoincrement=False, nullable=True
        ),
        sa.Column("request_id", sa.String(), autoincrement=False, nullable=True),
        sa.Column(
            "payable_amount",
            sa.Numeric(precision=15, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "receivable_amount",
            sa.Numeric(precision=15, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("insured_name", sa.String(), autoincrement=False, nullable=True),
        sa.Column(
            "boolean_reinsurance_involved",
            sa.Boolean(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "int_ri_payable_amount",
            sa.Numeric(precision=15, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "int_ri_receivable_amount",
            sa.Numeric(precision=15, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("statement", sa.String(), autoincrement=False, nullable=True),
        sa.Column("confirmation", sa.String(), autoincrement=False, nullable=True),
        sa.Column("ri_confirmation", sa.String(), autoincrement=False, nullable=True),
        sa.Column("current_status", sa.String(), autoincrement=False, nullable=True),
        sa.Column("utr_number", sa.String(), autoincrement=False, nullable=True),
        sa.Column("created_by", sa.String(), autoincrement=False, nullable=True),
        sa.Column(
            "date_created_date", sa.DateTime(), autoincrement=False, nullable=True
        ),
        sa.Column("updated_by", sa.String(), autoincrement=False, nullable=True),
        sa.Column("updated_on", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint(
            "id", "transaction_id", name=op.f("pk_coinsurance_version")
        ),
    )
    with op.batch_alter_table("coinsurance_version", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_coinsurance_version_end_transaction_id"),
            ["end_transaction_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_coinsurance_version_operation_type"),
            ["operation_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_coinsurance_version_transaction_id"),
            ["transaction_id"],
            unique=False,
        )

    with op.batch_alter_table("coinsurance", schema=None) as batch_op:
        batch_op.add_column(sa.Column("updated_by", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("updated_on", sa.DateTime(), nullable=True))
        batch_op.alter_column(
            "uiic_regional_code", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "uiic_office_code", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "follower_company_name", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "follower_office_code", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "type_of_transaction", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "current_status", existing_type=sa.VARCHAR(), nullable=False
        )

    with op.batch_alter_table(
        "coinsurance_balance_general_ledger_code_flag_sheet", schema=None
    ) as batch_op:
        batch_op.alter_column("gl_code", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("description", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table(
        "coinsurance_balance_zone_flag_sheet", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "regional_code", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("zone", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table("coinsurance_balances", schema=None) as batch_op:
        batch_op.alter_column("period", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("coinsurance_bank_mandate", schema=None) as batch_op:
        batch_op.alter_column(
            "company_name", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("office_code", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("bank_name", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("ifsc_code", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "bank_account_number", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "bank_mandate", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("remarks", existing_type=sa.TEXT(), nullable=False)

    with op.batch_alter_table("coinsurance_cash_call", schema=None) as batch_op:
        batch_op.alter_column("txt_hub", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("txt_ro_code", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("txt_oo_code", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "str_leader_follower", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "txt_insured_name", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "date_policy_start_date", existing_type=sa.DATE(), nullable=False
        )
        batch_op.alter_column(
            "date_policy_end_date", existing_type=sa.DATE(), nullable=False
        )
        batch_op.alter_column(
            "amount_total_paid",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column("txt_remarks", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column(
            "txt_coinsurer_name", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "percent_share",
            existing_type=sa.NUMERIC(precision=5, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "amount_of_share",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "txt_request_id", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "date_of_cash_call_raised", existing_type=sa.DATE(), nullable=False
        )
        batch_op.alter_column(
            "txt_current_status", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "txt_utr_number", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.drop_column("deleted_by")
        batch_op.drop_column("deleted_on")

    with op.batch_alter_table("coinsurance_log", schema=None) as batch_op:
        batch_op.alter_column(
            "coinsurance_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "uiic_regional_code", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "uiic_office_code", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "follower_company_name", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "follower_office_code", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "type_of_transaction", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "current_status", existing_type=sa.VARCHAR(), nullable=False
        )

    with op.batch_alter_table("coinsurance_receipts", schema=None) as batch_op:
        batch_op.alter_column("description", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "company_name", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "credit", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
        )
        batch_op.alter_column("value_date", existing_type=sa.DATE(), nullable=False)
        batch_op.alter_column(
            "reference_no", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "transaction_code", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("status", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table(
        "coinsurance_receipts_journal_voucher", schema=None
    ) as batch_op:
        batch_op.alter_column("gl_code", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table("coinsurance_token_request_id", schema=None) as batch_op:
        batch_op.alter_column(
            "hub_office_code", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "company_name", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "coinsurer_office_code", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "name_of_insured", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("request_id", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "amount", existing_type=sa.NUMERIC(precision=15, scale=2), nullable=False
        )
        batch_op.alter_column(
            "type_of_amount", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("gl_code", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("remarks", existing_type=sa.TEXT(), nullable=False)

    with op.batch_alter_table("payment_gateway_tieup", schema=None) as batch_op:
        batch_op.drop_column("deleted_by")
        batch_op.drop_column("date_deleted_date")

    with op.batch_alter_table("remarks", schema=None) as batch_op:
        batch_op.alter_column(
            "coinsurance_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column("remarks", existing_type=sa.TEXT(), nullable=False)
        batch_op.create_foreign_key(
            batch_op.f("fk_remarks_coinsurance_id_coinsurance"),
            "coinsurance",
            ["coinsurance_id"],
            ["id"],
        )

    with op.batch_alter_table("settlement", schema=None) as batch_op:
        batch_op.alter_column(
            "name_of_company", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "date_of_settlement", existing_type=sa.DATE(), nullable=False
        )
        batch_op.alter_column(
            "settled_amount",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column("utr_number", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "type_of_transaction", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("notes", existing_type=sa.TEXT(), nullable=False)
        batch_op.drop_column("deleted_by")
        batch_op.drop_column("deleted_on")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settlement", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "deleted_on", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column("deleted_by", sa.VARCHAR(), autoincrement=False, nullable=True)
        )
        batch_op.alter_column("notes", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column(
            "type_of_transaction", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("utr_number", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "settled_amount",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "date_of_settlement", existing_type=sa.DATE(), nullable=True
        )
        batch_op.alter_column(
            "name_of_company", existing_type=sa.VARCHAR(), nullable=True
        )

    with op.batch_alter_table("remarks", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_remarks_coinsurance_id_coinsurance"), type_="foreignkey"
        )
        batch_op.alter_column("remarks", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column(
            "coinsurance_id", existing_type=sa.INTEGER(), nullable=True
        )

    with op.batch_alter_table("payment_gateway_tieup", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "date_deleted_date",
                postgresql.TIMESTAMP(),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column("deleted_by", sa.VARCHAR(), autoincrement=False, nullable=True)
        )

    with op.batch_alter_table("coinsurance_token_request_id", schema=None) as batch_op:
        batch_op.alter_column("remarks", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("gl_code", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "type_of_amount", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "amount", existing_type=sa.NUMERIC(precision=15, scale=2), nullable=True
        )
        batch_op.alter_column("request_id", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "name_of_insured", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "coinsurer_office_code", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("company_name", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "hub_office_code", existing_type=sa.VARCHAR(), nullable=True
        )

    with op.batch_alter_table(
        "coinsurance_receipts_journal_voucher", schema=None
    ) as batch_op:
        batch_op.alter_column("gl_code", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("coinsurance_receipts", schema=None) as batch_op:
        batch_op.alter_column("status", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "transaction_code", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("reference_no", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("value_date", existing_type=sa.DATE(), nullable=True)
        batch_op.alter_column(
            "credit", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
        )
        batch_op.alter_column("company_name", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("description", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("coinsurance_log", schema=None) as batch_op:
        batch_op.alter_column(
            "current_status", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "type_of_transaction", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "follower_office_code", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "follower_company_name", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "uiic_office_code", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "uiic_regional_code", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "coinsurance_id", existing_type=sa.INTEGER(), nullable=True
        )

    with op.batch_alter_table("coinsurance_cash_call", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "deleted_on", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column("deleted_by", sa.VARCHAR(), autoincrement=False, nullable=True)
        )
        batch_op.alter_column(
            "txt_utr_number", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "txt_current_status", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "date_of_cash_call_raised", existing_type=sa.DATE(), nullable=True
        )
        batch_op.alter_column(
            "txt_request_id", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "amount_of_share",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "percent_share",
            existing_type=sa.NUMERIC(precision=5, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "txt_coinsurer_name", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("txt_remarks", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column(
            "amount_total_paid",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "date_policy_end_date", existing_type=sa.DATE(), nullable=True
        )
        batch_op.alter_column(
            "date_policy_start_date", existing_type=sa.DATE(), nullable=True
        )
        batch_op.alter_column(
            "txt_insured_name", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "str_leader_follower", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("txt_oo_code", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("txt_ro_code", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("txt_hub", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("coinsurance_bank_mandate", schema=None) as batch_op:
        batch_op.alter_column("remarks", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("bank_mandate", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "bank_account_number", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("ifsc_code", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("bank_name", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("office_code", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("company_name", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("coinsurance_balances", schema=None) as batch_op:
        batch_op.alter_column("period", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table(
        "coinsurance_balance_zone_flag_sheet", schema=None
    ) as batch_op:
        batch_op.alter_column("zone", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "regional_code", existing_type=sa.VARCHAR(), nullable=True
        )

    with op.batch_alter_table(
        "coinsurance_balance_general_ledger_code_flag_sheet", schema=None
    ) as batch_op:
        batch_op.alter_column("description", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("gl_code", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("coinsurance", schema=None) as batch_op:
        batch_op.alter_column(
            "current_status", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "type_of_transaction", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "follower_office_code", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "follower_company_name", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "uiic_office_code", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "uiic_regional_code", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.drop_column("updated_on")
        batch_op.drop_column("updated_by")

    with op.batch_alter_table("coinsurance_version", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_coinsurance_version_transaction_id"))
        batch_op.drop_index(batch_op.f("ix_coinsurance_version_operation_type"))
        batch_op.drop_index(batch_op.f("ix_coinsurance_version_end_transaction_id"))

    op.drop_table("coinsurance_version")
    # ### end Alembic commands ###
