"""empty message

Revision ID: 214385e8432c
Revises: 3d2e4d08523c
Create Date: 2025-12-10 17:55:46.970477

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "214385e8432c"
down_revision = "3d2e4d08523c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "change_instruction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("ticket_date", sa.Date(), nullable=False),
        sa.Column("ticket_number", sa.String(), nullable=False),
        sa.Column("ci_document", sa.String(), nullable=True),
        sa.Column("ci_number", sa.String(), nullable=True),
        sa.Column("current_status", sa.String(), nullable=False),
        sa.Column("approach_note_date", sa.Date(), nullable=True),
        sa.Column("approach_note_document", sa.String(), nullable=True),
        sa.Column("approach_note_approval_date", sa.Date(), nullable=True),
        sa.Column("uat_testing_date", sa.Date(), nullable=True),
        sa.Column("uat_remarks", sa.Text(), nullable=True),
        sa.Column("pilot_deployment_date", sa.Date(), nullable=True),
        sa.Column("production_deployment_date", sa.Date(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_instruction")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("change_instruction")
    # ### end Alembic commands ###
