"""empty message

Revision ID: 28f6fdb1c41a
Revises: 7e5658b31400
Create Date: 2025-01-06 11:29:34.274487

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "28f6fdb1c41a"
down_revision = "7e5658b31400"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pool_credits_journal_voucher",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("str_regional_office_code", sa.String(), nullable=True),
        sa.Column("gl_code", sa.String(), nullable=True),
        sa.Column("sl_code", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pool_credits_journal_voucher")),
        sa.UniqueConstraint(
            "str_regional_office_code",
            name=op.f("uq_pool_credits_journal_voucher_str_regional_office_code"),
        ),
    )
    with op.batch_alter_table("attendance_register", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("date_of_joining_current_cadre", sa.Date(), nullable=True)
        )

    with op.batch_alter_table("employee_data", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("date_of_joining_current_cadre", sa.Date(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("employee_data", schema=None) as batch_op:
        batch_op.drop_column("date_of_joining_current_cadre")

    with op.batch_alter_table("attendance_register", schema=None) as batch_op:
        batch_op.drop_column("date_of_joining_current_cadre")

    op.drop_table("pool_credits_journal_voucher")
    # ### end Alembic commands ###
