"""empty message

Revision ID: 2f1ef4063bfe
Revises: 1b04f2e51aad
Create Date: 2024-10-28 18:49:52.436425

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2f1ef4063bfe"
down_revision = "1b04f2e51aad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("coinsurance_receipts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("book_date", sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("coinsurance_receipts", schema=None) as batch_op:
        batch_op.drop_column("book_date")

    # ### end Alembic commands ###
