"""empty message

Revision ID: 334b7aa50e00
Revises: 57711195a80b
Create Date: 2024-04-10 12:04:44.204334

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "334b7aa50e00"
down_revision = "57711195a80b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outstanding_expenses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("str_regional_office_code", sa.String(), nullable=True),
        sa.Column("str_operating_office_code", sa.String(), nullable=True),
        sa.Column("str_party_type", sa.String(), nullable=True),
        sa.Column("str_party_id", sa.String(), nullable=True),
        sa.Column("str_party_name", sa.String(), nullable=True),
        sa.Column(
            "float_gross_amount", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column("bool_tds_involved", sa.Boolean(), nullable=True),
        sa.Column("float_tds_amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("float_net_amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("str_section", sa.String(), nullable=True),
        sa.Column("str_pan_number", sa.String(), nullable=True),
        sa.Column("str_nature_of_payment", sa.String(), nullable=True),
        sa.Column("str_narration", sa.Text(), nullable=True),
        sa.Column("date_payment_date", sa.Date(), nullable=True),
        sa.Column("date_date_of_creation", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outstanding_expenses")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("outstanding_expenses")
    # ### end Alembic commands ###
