"""empty message

Revision ID: 3cb809e3eb14
Revises: 214385e8432c
Create Date: 2026-01-05 11:16:03.233644

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3cb809e3eb14"
down_revision = "214385e8432c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_recon_imprest_summary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("regional_office", sa.String(), nullable=False),
        sa.Column("operating_office", sa.String(), nullable=False),
        sa.Column("month", sa.String(), nullable=False),
        sa.Column("purpose_of_bank_account", sa.String(), nullable=False),
        sa.Column("imprest_bank_name", sa.String(), nullable=False),
        sa.Column("imprest_bank_branch_name", sa.String(), nullable=True),
        sa.Column("imprest_bank_branch_location", sa.String(), nullable=True),
        sa.Column("imprest_bank_account_type", sa.String(), nullable=True),
        sa.Column("imprest_bank_account_number", sa.String(), nullable=False),
        sa.Column("imprest_bank_ifsc_code", sa.String(), nullable=True),
        sa.Column("imprest_brs_month_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_recon_imprest_summary")),
    )
    op.create_table(
        "bank_recon_local_collection_summary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("regional_office", sa.String(), nullable=False),
        sa.Column("operating_office", sa.String(), nullable=False),
        sa.Column("month", sa.String(), nullable=False),
        sa.Column("purpose_of_bank_account", sa.String(), nullable=False),
        sa.Column("local_collection_bank_name", sa.String(), nullable=False),
        sa.Column("local_collection_bank_branch_name", sa.String(), nullable=True),
        sa.Column("local_collection_bank_branch_location", sa.String(), nullable=True),
        sa.Column("local_collection_bank_account_type", sa.String(), nullable=True),
        sa.Column("local_collection_bank_account_number", sa.String(), nullable=False),
        sa.Column("local_collection_bank_ifsc_code", sa.String(), nullable=True),
        sa.Column("local_collection_brs_month_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_bank_recon_local_collection_summary")
        ),
    )
    op.create_table(
        "lien_regional_office_email_address",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ro_code", sa.String(), nullable=True),
        sa.Column("ro_name", sa.String(), nullable=True),
        sa.Column("ro_email_address", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_lien_regional_office_email_address")
        ),
    )
    op.create_table(
        "mail_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("smtp_server", sa.String(), nullable=False),
        sa.Column("smtp_port", sa.Integer(), nullable=False),
        sa.Column("use_tls", sa.Boolean(), nullable=False),
        sa.Column("use_ssl", sa.Boolean(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("default_sender", sa.String(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_config")),
    )
    op.create_table(
        "bank_recon_imprest_details",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("summary_id", sa.Integer(), nullable=False),
        sa.Column("opening_balance", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("fund_transfer", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("cheques_issued", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column(
            "cheques_cancelled", sa.Numeric(precision=15, scale=2), nullable=False
        ),
        sa.Column("bank_charges", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column(
            "closing_balance_gl", sa.Numeric(precision=15, scale=2), nullable=False
        ),
        sa.Column(
            "cheques_unencashed", sa.Numeric(precision=15, scale=2), nullable=False
        ),
        sa.Column(
            "closing_balance_bank", sa.Numeric(precision=15, scale=2), nullable=False
        ),
        sa.Column("remarks", sa.Text(), nullable=False),
        sa.Column("prepared_by_employee_name", sa.String(), nullable=False),
        sa.Column("prepared_by_employee_number", sa.String(), nullable=False),
        sa.Column("bank_statement", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["summary_id"],
            ["bank_recon_imprest_summary.id"],
            name=op.f(
                "fk_bank_recon_imprest_details_summary_id_bank_recon_imprest_summary"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_recon_imprest_details")),
    )
    op.create_table(
        "bank_recon_local_collection_details",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("brs_id", sa.Integer(), nullable=False),
        sa.Column("opening_balance", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("opening_on_hand", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("transactions", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("cancellations", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("fund_transfer", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("bank_charges", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("closing_on_hand", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("closing_balance", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column(
            "deposited_not_credited", sa.Numeric(precision=15, scale=2), nullable=False
        ),
        sa.Column("short_credited", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("excess_credited", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column(
            "balance_as_per_bank", sa.Numeric(precision=15, scale=2), nullable=False
        ),
        sa.Column("bank_statement", sa.String(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("prepared_by_employee_name", sa.String(), nullable=False),
        sa.Column("prepared_by_employee_number", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["brs_id"],
            ["bank_recon_local_collection_summary.id"],
            name=op.f(
                "fk_bank_recon_local_collection_details_brs_id_bank_recon_local_collection_summary"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_bank_recon_local_collection_details")
        ),
    )
    op.create_table(
        "bank_recon_imprest_unencashed_details",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("voucher_number", sa.String(), nullable=False),
        sa.Column("voucher_date", sa.Date(), nullable=False),
        sa.Column("instrument_number", sa.String(), nullable=False),
        sa.Column("instrument_date", sa.Date(), nullable=False),
        sa.Column(
            "instrument_amount", sa.Numeric(precision=15, scale=2), nullable=False
        ),
        sa.Column("payee_name", sa.String(), nullable=False),
        sa.Column("remarks", sa.Text(), nullable=False),
        sa.Column("instrument_status", sa.String(), nullable=True),
        sa.Column("brs_details_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["brs_details_id"],
            ["bank_recon_imprest_details.id"],
            name=op.f(
                "fk_bank_recon_imprest_unencashed_details_brs_details_id_bank_recon_imprest_details"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_bank_recon_imprest_unencashed_details")
        ),
    )
    op.create_table(
        "bank_recon_local_collection_excess_credit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("brs_details_id", sa.Integer(), nullable=False),
        sa.Column("mode_of_collection", sa.String(), nullable=False),
        sa.Column("instrument_number", sa.String(), nullable=True),
        sa.Column(
            "instrument_amount", sa.Numeric(precision=15, scale=2), nullable=False
        ),
        sa.Column("date_of_instrument", sa.Date(), nullable=True),
        sa.Column("date_of_collection", sa.Date(), nullable=False),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["brs_details_id"],
            ["bank_recon_local_collection_details.id"],
            name=op.f(
                "fk_bank_recon_local_collection_excess_credit_brs_details_id_bank_recon_local_collection_details"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_bank_recon_local_collection_excess_credit")
        ),
    )
    op.create_table(
        "bank_recon_local_collection_outstanding",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("brs_details_id", sa.Integer(), nullable=False),
        sa.Column("mode_of_collection", sa.String(), nullable=False),
        sa.Column("instrument_number", sa.String(), nullable=True),
        sa.Column(
            "instrument_amount", sa.Numeric(precision=15, scale=2), nullable=False
        ),
        sa.Column("date_of_instrument", sa.Date(), nullable=True),
        sa.Column("date_of_collection", sa.Date(), nullable=False),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["brs_details_id"],
            ["bank_recon_local_collection_details.id"],
            name=op.f(
                "fk_bank_recon_local_collection_outstanding_brs_details_id_bank_recon_local_collection_details"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_bank_recon_local_collection_outstanding")
        ),
    )
    op.create_table(
        "bank_recon_local_collection_short_credit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("brs_details_id", sa.Integer(), nullable=False),
        sa.Column("mode_of_collection", sa.String(), nullable=False),
        sa.Column("instrument_number", sa.String(), nullable=True),
        sa.Column(
            "instrument_amount", sa.Numeric(precision=15, scale=2), nullable=False
        ),
        sa.Column("date_of_instrument", sa.Date(), nullable=True),
        sa.Column("date_of_collection", sa.Date(), nullable=False),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["brs_details_id"],
            ["bank_recon_local_collection_details.id"],
            name=op.f(
                "fk_bank_recon_local_collection_short_credit_brs_details_id_bank_recon_local_collection_details"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_bank_recon_local_collection_short_credit")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bank_recon_local_collection_short_credit")
    op.drop_table("bank_recon_local_collection_outstanding")
    op.drop_table("bank_recon_local_collection_excess_credit")
    op.drop_table("bank_recon_imprest_unencashed_details")
    op.drop_table("bank_recon_local_collection_details")
    op.drop_table("bank_recon_imprest_details")
    op.drop_table("mail_config")
    op.drop_table("lien_regional_office_email_address")
    op.drop_table("bank_recon_local_collection_summary")
    op.drop_table("bank_recon_imprest_summary")
    # ### end Alembic commands ###
