"""empty message

Revision ID: 3de9bab827fd
Revises:
Create Date: 2024-03-18 11:41:49.317561

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3de9bab827fd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_base",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("topic", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("knowledge_base_document", sa.String(), nullable=True),
        sa.Column("is_visible", sa.Boolean(), nullable=True),
        sa.Column("status", sa.Boolean(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_base")),
    )
    with op.batch_alter_table("brs_month", schema=None) as batch_op:
        batch_op.alter_column(
            "int_opening_balance",
            existing_type=sa.NUMERIC(precision=10, scale=2),
            type_=sa.Numeric(precision=15, scale=2),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "int_opening_on_hand",
            existing_type=sa.NUMERIC(precision=10, scale=2),
            type_=sa.Numeric(precision=15, scale=2),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "int_transactions",
            existing_type=sa.NUMERIC(precision=10, scale=2),
            type_=sa.Numeric(precision=15, scale=2),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "int_cancellations",
            existing_type=sa.NUMERIC(precision=10, scale=2),
            type_=sa.Numeric(precision=15, scale=2),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "int_fund_transfer",
            existing_type=sa.NUMERIC(precision=10, scale=2),
            type_=sa.Numeric(precision=15, scale=2),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "int_bank_charges",
            existing_type=sa.NUMERIC(precision=10, scale=2),
            type_=sa.Numeric(precision=15, scale=2),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "int_closing_on_hand",
            existing_type=sa.NUMERIC(precision=10, scale=2),
            type_=sa.Numeric(precision=15, scale=2),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "int_closing_balance",
            existing_type=sa.NUMERIC(precision=10, scale=2),
            type_=sa.Numeric(precision=15, scale=2),
            existing_nullable=True,
        )

    with op.batch_alter_table("outstanding", schema=None) as batch_op:
        batch_op.alter_column(
            "instrument_amount",
            existing_type=sa.NUMERIC(precision=10, scale=2),
            type_=sa.Numeric(precision=15, scale=2),
            existing_nullable=True,
        )

    with op.batch_alter_table("settlement", schema=None) as batch_op:
        batch_op.add_column(sa.Column("notes", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settlement", schema=None) as batch_op:
        batch_op.drop_column("notes")

    with op.batch_alter_table("outstanding", schema=None) as batch_op:
        batch_op.alter_column(
            "instrument_amount",
            existing_type=sa.Numeric(precision=15, scale=2),
            type_=sa.NUMERIC(precision=10, scale=2),
            existing_nullable=True,
        )

    with op.batch_alter_table("brs_month", schema=None) as batch_op:
        batch_op.alter_column(
            "int_closing_balance",
            existing_type=sa.Numeric(precision=15, scale=2),
            type_=sa.NUMERIC(precision=10, scale=2),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "int_closing_on_hand",
            existing_type=sa.Numeric(precision=15, scale=2),
            type_=sa.NUMERIC(precision=10, scale=2),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "int_bank_charges",
            existing_type=sa.Numeric(precision=15, scale=2),
            type_=sa.NUMERIC(precision=10, scale=2),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "int_fund_transfer",
            existing_type=sa.Numeric(precision=15, scale=2),
            type_=sa.NUMERIC(precision=10, scale=2),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "int_cancellations",
            existing_type=sa.Numeric(precision=15, scale=2),
            type_=sa.NUMERIC(precision=10, scale=2),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "int_transactions",
            existing_type=sa.Numeric(precision=15, scale=2),
            type_=sa.NUMERIC(precision=10, scale=2),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "int_opening_on_hand",
            existing_type=sa.Numeric(precision=15, scale=2),
            type_=sa.NUMERIC(precision=10, scale=2),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "int_opening_balance",
            existing_type=sa.Numeric(precision=15, scale=2),
            type_=sa.NUMERIC(precision=10, scale=2),
            existing_nullable=True,
        )

    op.drop_table("knowledge_base")
    # ### end Alembic commands ###
