"""empty message

Revision ID: 438d906a7ef1
Revises: 28f6fdb1c41a
Create Date: 2025-02-03 12:43:58.096071

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "438d906a7ef1"
down_revision = "28f6fdb1c41a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coinsurance_receipts_journal_voucher",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pattern", sa.String(), nullable=True),
        sa.Column("company_name", sa.String(), nullable=True),
        sa.Column("gl_code", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_coinsurance_receipts_journal_voucher")
        ),
    )
    with op.batch_alter_table("leave_application", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("date_of_joining_current_cadre", sa.Date(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leave_application", schema=None) as batch_op:
        batch_op.drop_column("date_of_joining_current_cadre")

    op.drop_table("coinsurance_receipts_journal_voucher")
    # ### end Alembic commands ###
