"""empty message

Revision ID: 43d47f14b2a9
Revises: 82936fc825bf
Create Date: 2024-08-16 12:14:14.131096

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "43d47f14b2a9"
down_revision = "82936fc825bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pool_credits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_uploaded_date", sa.Date(), nullable=True),
        sa.Column("book_date", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("ledger_balance", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("credit", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("debit", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("value_date", sa.Date(), nullable=True),
        sa.Column("reference_no", sa.String(), nullable=True),
        sa.Column("transaction_branch", sa.Text(), nullable=True),
        sa.Column("flag_description", sa.Text(), nullable=True),
        sa.Column("str_regional_office_code", sa.String(), nullable=True),
        sa.Column("text_remarks", sa.Text(), nullable=True),
        sa.Column("bool_jv_passed", sa.Boolean(), nullable=True),
        sa.Column("date_created_date", sa.DateTime(), nullable=True),
        sa.Column("date_updated_date", sa.DateTime(), nullable=True),
        sa.Column("date_deleted_date", sa.DateTime(), nullable=True),
        sa.Column("date_jv_passed_date", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.Column("jv_passed_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pool_credits")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pool_credits")
    # ### end Alembic commands ###
