"""Add auditor certificate models

Revision ID: 46c4cc468740
Revises: 1d77e21c2f6f
Create Date: 2026-02-16 16:53:11.956218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c4cc468740'
down_revision = '1d77e21c2f6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditor_certificate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ro_code', sa.String(), nullable=False),
    sa.Column('ro_name', sa.String(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('date_of_request', sa.Date(), nullable=False),
    sa.Column('bid_closing_date', sa.Date(), nullable=True),
    sa.Column('certificate_issued_date', sa.Date(), nullable=True),
    sa.Column('invoice_received_date', sa.Date(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('disbursement_date', sa.Date(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('date_of_payment', sa.Date(), nullable=True),
    sa.Column('utr_number', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auditor_certificate'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auditor_certificate')
    # ### end Alembic commands ###
