"""empty message

Revision ID: 4acbc523056a
Revises: 43d47f14b2a9
Create Date: 2024-09-16 11:14:42.129679

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4acbc523056a"
down_revision = "43d47f14b2a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pool_credits_portal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("txt_reference_number", sa.String(), nullable=True),
        sa.Column("date_value_date", sa.Date(), nullable=True),
        sa.Column("amount_credit", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("txt_name_of_remitter", sa.String(), nullable=True),
        sa.Column("date_created_date", sa.DateTime(), nullable=True),
        sa.Column("date_updated_date", sa.DateTime(), nullable=True),
        sa.Column("date_deleted_date", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pool_credits_portal")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pool_credits_portal")
    # ### end Alembic commands ###
