"""empty message

Revision ID: 50e01977b341
Revises: 16861445f53f
Create Date: 2024-10-03 12:12:28.465429

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "50e01977b341"
down_revision = "16861445f53f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coinsurance_receipts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("company_name", sa.String(), nullable=True),
        sa.Column("credit", sa.Float(), nullable=True),
        sa.Column("value_date", sa.Date(), nullable=True),
        sa.Column("reference_no", sa.String(), nullable=True),
        sa.Column("transaction_code", sa.String(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("receipting_office", sa.String(), nullable=True),
        sa.Column("date_of_receipt", sa.Date(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coinsurance_receipts")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("coinsurance_receipts")
    # ### end Alembic commands ###
