"""empty message

Revision ID: 57711195a80b
Revises: 3de9bab827fd
Create Date: 2024-04-05 18:02:58.552266

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "57711195a80b"
down_revision = "3de9bab827fd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_guarantee",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ro_code", sa.String(), nullable=True),
        sa.Column("oo_code", sa.String(), nullable=True),
        sa.Column("customer_name", sa.String(), nullable=True),
        sa.Column("customer_id", sa.String(), nullable=True),
        sa.Column("debit_amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("credit_amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("payment_id", sa.String(), nullable=True),
        sa.Column("date_of_payment", sa.Date(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("course_of_action", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_guarantee")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bank_guarantee")
    # ### end Alembic commands ###
