"""Funds: Add boolean for outflow label for merging with AXIS NEFT

Revision ID: 5ae9796ab282
Revises: 172c94d6901a
Create Date: 2026-06-13 11:55:35.060300

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5ae9796ab282"
down_revision = "172c94d6901a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fund_outflow_label", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("merge_with_axis_neft", sa.Boolean(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fund_outflow_label", schema=None) as batch_op:
        batch_op.drop_column("merge_with_axis_neft")

    # ### end Alembic commands ###
