"""empty message

Revision ID: 612021ae9b0e
Revises: 6ed7bfee96ec
Create Date: 2024-06-10 15:46:37.003500

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "612021ae9b0e"
down_revision = "6ed7bfee96ec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "announcements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("txt_title", sa.Text(), nullable=True),
        sa.Column("txt_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_announcements")),
    )
    op.create_table(
        "coinsurance_cash_call",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("txt_hub", sa.String(), nullable=True),
        sa.Column("txt_ro_code", sa.String(), nullable=True),
        sa.Column("txt_oo_code", sa.String(), nullable=True),
        sa.Column("txt_insured_name", sa.String(), nullable=True),
        sa.Column("date_policy_start_date", sa.Date(), nullable=True),
        sa.Column("date_policy_end_date", sa.Date(), nullable=True),
        sa.Column(
            "amount_total_paid", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column("txt_remarks", sa.Text(), nullable=True),
        sa.Column("date_claim_payment", sa.Date(), nullable=True),
        sa.Column("txt_coinsurer_name", sa.String(), nullable=True),
        sa.Column("percent_share", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("amount_of_share", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("txt_request_id", sa.String(), nullable=True),
        sa.Column("date_of_cash_call_raised", sa.Date(), nullable=True),
        sa.Column("txt_current_status", sa.String(), nullable=True),
        sa.Column("txt_utr_number", sa.String(), nullable=True),
        sa.Column("date_of_cash_call_settlement", sa.Date(), nullable=True),
        sa.Column(
            "amount_settlement", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.Column("deleted_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coinsurance_cash_call")),
    )
    op.create_table(
        "delete_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("txt_month", sa.String(), nullable=True),
        sa.Column("bool_enable_delete", sa.Boolean(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delete_entries")),
    )
    op.create_table(
        "fund_amount_given_to_investment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_given_to_investment", sa.Date(), nullable=True),
        sa.Column(
            "float_amount_given_to_investment",
            sa.Numeric(precision=20, scale=2),
            nullable=True,
        ),
        sa.Column("date_expected_date_of_return", sa.Date(), nullable=True),
        sa.Column("text_remarks", sa.Text(), nullable=True),
        sa.Column("current_status", sa.String(), nullable=True),
        sa.Column("date_created_date", sa.DateTime(), nullable=True),
        sa.Column("date_updated_date", sa.DateTime(), nullable=True),
        sa.Column("date_deleted_date", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fund_amount_given_to_investment")),
    )
    op.create_table(
        "fund_bank_account_numbers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("outflow_description", sa.String(), nullable=True),
        sa.Column("bank_name", sa.String(), nullable=True),
        sa.Column("bank_type", sa.String(), nullable=True),
        sa.Column("bank_account_number", sa.String(), nullable=True),
        sa.Column("current_status", sa.String(), nullable=True),
        sa.Column("date_created_date", sa.DateTime(), nullable=True),
        sa.Column("date_updated_date", sa.DateTime(), nullable=True),
        sa.Column("date_deleted_date", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fund_bank_account_numbers")),
    )
    op.create_table(
        "fund_bank_statement",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_uploaded_date", sa.Date(), nullable=True),
        sa.Column("book_date", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("ledger_balance", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("credit", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("debit", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("value_date", sa.Date(), nullable=True),
        sa.Column("reference_no", sa.String(), nullable=True),
        sa.Column("transaction_branch", sa.Text(), nullable=True),
        sa.Column("flag_description", sa.Text(), nullable=True),
        sa.Column("text_remarks", sa.Text(), nullable=True),
        sa.Column("current_status", sa.String(), nullable=True),
        sa.Column("date_created_date", sa.DateTime(), nullable=True),
        sa.Column("date_updated_date", sa.DateTime(), nullable=True),
        sa.Column("date_deleted_date", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fund_bank_statement")),
    )
    op.create_table(
        "fund_daily_outflow",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("outflow_date", sa.Date(), nullable=True),
        sa.Column("outflow_amount", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("outflow_description", sa.String(), nullable=True),
        sa.Column("text_remarks", sa.Text(), nullable=True),
        sa.Column("current_status", sa.String(), nullable=True),
        sa.Column("date_created_date", sa.DateTime(), nullable=True),
        sa.Column("date_updated_date", sa.DateTime(), nullable=True),
        sa.Column("date_deleted_date", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fund_daily_outflow")),
    )
    op.create_table(
        "fund_daily_sheet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_current_date", sa.Date(), nullable=True),
        sa.Column("text_major_collections", sa.Text(), nullable=True),
        sa.Column("text_major_payments", sa.Text(), nullable=True),
        sa.Column(
            "float_amount_given_to_investments",
            sa.Numeric(precision=20, scale=2),
            nullable=True,
        ),
        sa.Column(
            "float_amount_taken_from_investments",
            sa.Numeric(precision=20, scale=2),
            nullable=True,
        ),
        sa.Column(
            "float_amount_hdfc_closing_balance",
            sa.Numeric(precision=20, scale=2),
            nullable=True,
        ),
        sa.Column(
            "float_amount_investment_closing_balance",
            sa.Numeric(precision=20, scale=2),
            nullable=True,
        ),
        sa.Column("text_person1_name", sa.String(), nullable=True),
        sa.Column("text_person1_designation", sa.String(), nullable=True),
        sa.Column("text_person2_name", sa.String(), nullable=True),
        sa.Column("text_person2_designation", sa.String(), nullable=True),
        sa.Column("text_person3_name", sa.String(), nullable=True),
        sa.Column("text_person3_designation", sa.String(), nullable=True),
        sa.Column("text_person4_name", sa.String(), nullable=True),
        sa.Column("text_person4_designation", sa.String(), nullable=True),
        sa.Column("text_remarks", sa.Text(), nullable=True),
        sa.Column("current_status", sa.String(), nullable=True),
        sa.Column("date_created_date", sa.DateTime(), nullable=True),
        sa.Column("date_updated_date", sa.DateTime(), nullable=True),
        sa.Column("date_deleted_date", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fund_daily_sheet")),
    )
    op.create_table(
        "fund_flag_sheet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("flag_description", sa.Text(), nullable=True),
        sa.Column("flag_reg_exp", sa.Text(), nullable=True),
        sa.Column("text_remarks", sa.Text(), nullable=True),
        sa.Column("current_status", sa.String(), nullable=True),
        sa.Column("date_created_date", sa.DateTime(), nullable=True),
        sa.Column("date_updated_date", sa.DateTime(), nullable=True),
        sa.Column("date_deleted_date", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fund_flag_sheet")),
    )
    op.create_table(
        "fund_major_outgo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_of_outgo", sa.Date(), nullable=True),
        sa.Column(
            "float_expected_outgo", sa.Numeric(precision=20, scale=2), nullable=True
        ),
        sa.Column("text_dept", sa.Text(), nullable=True),
        sa.Column("text_remarks", sa.Text(), nullable=True),
        sa.Column("current_status", sa.String(), nullable=True),
        sa.Column("date_created_date", sa.DateTime(), nullable=True),
        sa.Column("date_updated_date", sa.DateTime(), nullable=True),
        sa.Column("date_deleted_date", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fund_major_outgo")),
    )
    op.create_table(
        "mis_tracker",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("txt_period", sa.String(), nullable=True),
        sa.Column("txt_mis_type", sa.String(), nullable=True),
        sa.Column("bool_mis_shared", sa.Boolean(), nullable=True),
        sa.Column("date_mis_shared", sa.DateTime(), nullable=True),
        sa.Column("mis_shared_by", sa.String(), nullable=True),
        sa.Column("bool_brs_completed", sa.Boolean(), nullable=True),
        sa.Column("date_brs_completed", sa.DateTime(), nullable=True),
        sa.Column("brs_completed_by", sa.String(), nullable=True),
        sa.Column("bool_jv_passed", sa.Boolean(), nullable=True),
        sa.Column("date_jv_passed", sa.DateTime(), nullable=True),
        sa.Column("jv_passed_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mis_tracker")),
    )
    with op.batch_alter_table("settlement", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_by", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("created_on", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("updated_by", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("updated_on", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("deleted_by", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("deleted_on", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settlement", schema=None) as batch_op:
        batch_op.drop_column("deleted_on")
        batch_op.drop_column("deleted_by")
        batch_op.drop_column("updated_on")
        batch_op.drop_column("updated_by")
        batch_op.drop_column("created_on")
        batch_op.drop_column("created_by")

    op.drop_table("mis_tracker")
    op.drop_table("fund_major_outgo")
    op.drop_table("fund_flag_sheet")
    op.drop_table("fund_daily_sheet")
    op.drop_table("fund_daily_outflow")
    op.drop_table("fund_bank_statement")
    op.drop_table("fund_bank_account_numbers")
    op.drop_table("fund_amount_given_to_investment")
    op.drop_table("delete_entries")
    op.drop_table("coinsurance_cash_call")
    op.drop_table("announcements")
    # ### end Alembic commands ###
