"""empty message

Revision ID: 625ad2328c2a
Revises: b6eba0e85c81
Create Date: 2025-06-10 11:14:04.820519

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "625ad2328c2a"
down_revision = "b6eba0e85c81"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coinsurance_balance_general_ledger_code_flag_sheet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gl_code", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("company_name", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_coinsurance_balance_general_ledger_code_flag_sheet")
        ),
    )
    op.create_table(
        "coinsurance_balance_zone_flag_sheet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("regional_code", sa.String(), nullable=True),
        sa.Column("zone", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_coinsurance_balance_zone_flag_sheet")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("coinsurance_balance_zone_flag_sheet")
    op.drop_table("coinsurance_balance_general_ledger_code_flag_sheet")
    # ### end Alembic commands ###
