"""empty message

Revision ID: 63040ebc6aba
Revises: 438d906a7ef1
Create Date: 2025-02-21 12:51:41.922260

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "63040ebc6aba"
down_revision = "438d906a7ef1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "privilege_leave_balance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("opening_balance", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("leave_accrued", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("leave_availed", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("leave_encashed", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("leave_lapsed", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("closing_balance", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.Column("calendar_year", sa.Integer(), nullable=True),
        sa.Column("employee_name", sa.String(), nullable=True),
        sa.Column("employee_number", sa.Integer(), nullable=True),
        sa.Column("employee_designation", sa.String(), nullable=True),
        sa.Column("employee_ro_code", sa.String(), nullable=True),
        sa.Column("employee_oo_code", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_privilege_leave_balance")),
    )
    op.create_table(
        "sick_leave_balance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("opening_balance", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("leave_accrued", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("leave_availed", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("leave_lapsed", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("closing_balance", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.Column("calendar_year", sa.Integer(), nullable=True),
        sa.Column("employee_name", sa.String(), nullable=True),
        sa.Column("employee_number", sa.Integer(), nullable=True),
        sa.Column("employee_designation", sa.String(), nullable=True),
        sa.Column("employee_ro_code", sa.String(), nullable=True),
        sa.Column("employee_oo_code", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sick_leave_balance")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sick_leave_balance")
    op.drop_table("privilege_leave_balance")
    # ### end Alembic commands ###
