"""empty message

Revision ID: 647c9eece076
Revises: 0c8ceb77480b
Create Date: 2024-12-26 19:25:44.091304

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "647c9eece076"
down_revision = "0c8ceb77480b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("knowledge_base", schema=None) as batch_op:
        batch_op.add_column(sa.Column("updated_by", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("updated_on", sa.DateTime(), nullable=True))

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("role", sa.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("role")

    with op.batch_alter_table("knowledge_base", schema=None) as batch_op:
        batch_op.drop_column("updated_on")
        batch_op.drop_column("updated_by")

    # ### end Alembic commands ###
