"""empty message

Revision ID: 6488aa5c39fb
Revises: 2f1ef4063bfe
Create Date: 2024-10-30 12:02:59.675479

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6488aa5c39fb"
down_revision = "2f1ef4063bfe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_by", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("created_on", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("updated_by", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("updated_on", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.drop_column("updated_on")
        batch_op.drop_column("updated_by")
        batch_op.drop_column("created_on")
        batch_op.drop_column("created_by")

    # ### end Alembic commands ###
