"""empty message

Revision ID: 64e1008171c0
Revises: 0cba317334d7
Create Date: 2025-10-13 11:34:56.683486

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "64e1008171c0"
down_revision = "0cba317334d7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "circular",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("month", sa.Integer(), nullable=True),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("reference_number", sa.String(), nullable=True),
        sa.Column("date_of_issue", sa.Date(), nullable=True),
        sa.Column("circular_title", sa.String(), nullable=True),
        sa.Column("issued_by_name", sa.String(), nullable=True),
        sa.Column("issued_by_designation", sa.String(), nullable=True),
        sa.Column("mode_of_dispatch", sa.String(), nullable=True),
        sa.Column("recipients", sa.String(), nullable=True),
        sa.Column("number_of_copies", sa.Integer(), nullable=True),
        sa.Column("date_of_acknowledgement", sa.Date(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("upload_document", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_circular")),
    )
    op.create_table(
        "inward_document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("month", sa.Integer(), nullable=True),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("reference_number", sa.String(), nullable=True),
        sa.Column("date_of_receipt", sa.Date(), nullable=True),
        sa.Column("time_of_receipt", sa.Time(), nullable=True),
        sa.Column("sender_name", sa.String(), nullable=True),
        sa.Column("sender_address", sa.Text(), nullable=True),
        sa.Column("mode_of_receipt", sa.String(), nullable=True),
        sa.Column("letter_reference_number", sa.String(), nullable=True),
        sa.Column("description_of_item", sa.Text(), nullable=True),
        sa.Column("recipient_name", sa.String(), nullable=True),
        sa.Column("received_by", sa.String(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("upload_document", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inward_document")),
    )
    op.create_table(
        "outward_document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("month", sa.Integer(), nullable=True),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("reference_number", sa.String(), nullable=True),
        sa.Column("date_of_dispatch", sa.Date(), nullable=True),
        sa.Column("time_of_dispatch", sa.Time(), nullable=True),
        sa.Column("recipient_name", sa.String(), nullable=True),
        sa.Column("recipient_address", sa.Text(), nullable=True),
        sa.Column("mode_of_dispatch", sa.String(), nullable=True),
        sa.Column("description_of_item", sa.Text(), nullable=True),
        sa.Column("sender_name", sa.String(), nullable=True),
        sa.Column("dispatched_by", sa.String(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("upload_document", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outward_document")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("outward_document")
    op.drop_table("inward_document")
    op.drop_table("circular")
    # ### end Alembic commands ###
