"""DD-Create RM email address model

Revision ID: 6a251427dea0
Revises: d51cadc7bc3c
Create Date: 2026-03-26 12:50:16.172873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a251427dea0'
down_revision = 'd51cadc7bc3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regional_manager_email_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_code', sa.String(), nullable=False),
    sa.Column('office_name', sa.String(), nullable=False),
    sa.Column('employee_name', sa.String(), nullable=True),
    sa.Column('employee_number', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regional_manager_email_address'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regional_manager_email_address')
    # ### end Alembic commands ###
