"""empty message

Revision ID: 6ed7bfee96ec
Revises: 334b7aa50e00
Create Date: 2024-04-15 11:36:11.491640

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6ed7bfee96ec"
down_revision = "334b7aa50e00"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outstanding_expenses", schema=None) as batch_op:
        batch_op.add_column(sa.Column("current_status", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outstanding_expenses", schema=None) as batch_op:
        batch_op.drop_column("current_status")

    # ### end Alembic commands ###
