"""empty message

Revision ID: 6fa3bd47d49e
Revises: 90e8789e9946
Create Date: 2025-07-16 11:44:13.649450

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6fa3bd47d49e"
down_revision = "90e8789e9946"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lien", schema=None) as batch_op:
        batch_op.add_column(sa.Column("lien_date", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("dd_date", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("department", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("case_title", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("date_of_lien_order", sa.Date(), nullable=True))
        batch_op.add_column(
            sa.Column("claim_already_paid_by_hub_office", sa.String(), nullable=True)
        )
        batch_op.add_column(sa.Column("claim_number", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("date_of_claim_registration", sa.Date(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("claim_disbursement_voucher", sa.String(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("lien_dd_reversal_order", sa.String(), nullable=True)
        )
        batch_op.add_column(sa.Column("appeal_given", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("appeal_copy", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("stay_obtained", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("stay_order", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("claim_accounting_voucher_number", sa.String(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("claim_accounting_voucher_date", sa.Date(), nullable=True)
        )
        batch_op.add_column(sa.Column("ho_tp_remarks", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("court_order_dd_reversal", sa.String(), nullable=True)
        )
        batch_op.drop_column("date_of_order")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lien", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("date_of_order", sa.DATE(), autoincrement=False, nullable=True)
        )
        batch_op.drop_column("court_order_dd_reversal")
        batch_op.drop_column("ho_tp_remarks")
        batch_op.drop_column("claim_accounting_voucher_date")
        batch_op.drop_column("claim_accounting_voucher_number")
        batch_op.drop_column("stay_order")
        batch_op.drop_column("stay_obtained")
        batch_op.drop_column("appeal_copy")
        batch_op.drop_column("appeal_given")
        batch_op.drop_column("lien_dd_reversal_order")
        batch_op.drop_column("claim_disbursement_voucher")
        batch_op.drop_column("date_of_claim_registration")
        batch_op.drop_column("claim_number")
        batch_op.drop_column("claim_already_paid_by_hub_office")
        batch_op.drop_column("date_of_lien_order")
        batch_op.drop_column("case_title")
        batch_op.drop_column("department")
        batch_op.drop_column("dd_date")
        batch_op.drop_column("lien_date")

    # ### end Alembic commands ###
