"""Create DD model

Revision ID: 7332e372079b
Revises: 3cb809e3eb14
Create Date: 2026-02-10 16:12:30.348114

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7332e372079b"
down_revision = "3cb809e3eb14"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "direct_debit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ro_name", sa.String(), nullable=False),
        sa.Column("ro_code", sa.String(), nullable=False),
        sa.Column("transaction_date", sa.Date(), nullable=False),
        sa.Column("particulars", sa.String(), nullable=False),
        sa.Column("debit", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("ho_iot_jv_number", sa.String(), nullable=True),
        sa.Column("ho_iot_jv_date", sa.Date(), nullable=True),
        sa.Column("bool_jv_passed", sa.Boolean(), nullable=False),
        sa.Column("jv_passed_as_on", sa.Date(), nullable=True),
        sa.Column("ro_jv_number", sa.String(), nullable=True),
        sa.Column("ro_jv_date", sa.String(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_direct_debit")),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("direct_debit")
    # ### end Alembic commands ###
