"""empty message

Revision ID: 7e5658b31400
Revises: 647c9eece076
Create Date: 2024-12-30 11:23:48.658237

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7e5658b31400"
down_revision = "647c9eece076"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attendance_register",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_of_attendance", sa.Date(), nullable=True),
        sa.Column("employee_name", sa.String(), nullable=True),
        sa.Column("employee_number", sa.Integer(), nullable=True),
        sa.Column("employee_designation", sa.String(), nullable=True),
        sa.Column("status_of_attendance", sa.String(), nullable=True),
        sa.Column("type_of_leave", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendance_register")),
    )
    op.create_table(
        "employee_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_name", sa.String(), nullable=True),
        sa.Column("employee_number", sa.Integer(), nullable=True),
        sa.Column("employee_designation", sa.String(), nullable=True),
        sa.Column("current_status", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_data")),
        sa.UniqueConstraint(
            "employee_number", name=op.f("uq_employee_data_employee_number")
        ),
    )
    op.create_table(
        "leave_application",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type_of_leave", sa.String(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "number_of_days_leave", sa.Numeric(precision=6, scale=2), nullable=True
        ),
        sa.Column(
            "number_of_days_off_duty", sa.Numeric(precision=6, scale=2), nullable=True
        ),
        sa.Column("employee_name", sa.String(), nullable=True),
        sa.Column("employee_number", sa.Integer(), nullable=True),
        sa.Column("employee_designation", sa.String(), nullable=True),
        sa.Column(
            "available_leave_credit", sa.Numeric(precision=6, scale=2), nullable=True
        ),
        sa.Column("purpose_of_leave", sa.Text(), nullable=True),
        sa.Column("leave_approved_by", sa.String(), nullable=True),
        sa.Column("leave_approver_designation", sa.String(), nullable=True),
        sa.Column(
            "list_attendance_register_days", sa.ARRAY(sa.Integer()), nullable=True
        ),
        sa.Column("current_status", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leave_application")),
    )
    op.create_table(
        "leave_balance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("calendar_year", sa.Integer(), nullable=True),
        sa.Column("employee_name", sa.String(), nullable=True),
        sa.Column("employee_number", sa.Integer(), nullable=True),
        sa.Column(
            "opening_casual_leave_balance",
            sa.Numeric(precision=6, scale=2),
            nullable=True,
        ),
        sa.Column(
            "opening_sick_leave_balance",
            sa.Numeric(precision=6, scale=2),
            nullable=True,
        ),
        sa.Column(
            "opening_rh_balance", sa.Numeric(precision=6, scale=2), nullable=True
        ),
        sa.Column(
            "opening_privileged_leave_balance",
            sa.Numeric(precision=6, scale=2),
            nullable=True,
        ),
        sa.Column(
            "current_casual_leave_balance",
            sa.Numeric(precision=6, scale=2),
            nullable=True,
        ),
        sa.Column(
            "current_sick_leave_balance",
            sa.Numeric(precision=6, scale=2),
            nullable=True,
        ),
        sa.Column(
            "current_rh_balance", sa.Numeric(precision=6, scale=2), nullable=True
        ),
        sa.Column(
            "current_privileged_leave_balance",
            sa.Numeric(precision=6, scale=2),
            nullable=True,
        ),
        sa.Column(
            "closing_casual_leave_balance",
            sa.Numeric(precision=6, scale=2),
            nullable=True,
        ),
        sa.Column(
            "closing_sick_leave_balance",
            sa.Numeric(precision=6, scale=2),
            nullable=True,
        ),
        sa.Column(
            "closing_rh_balance", sa.Numeric(precision=6, scale=2), nullable=True
        ),
        sa.Column(
            "closing_privileged_leave_balance",
            sa.Numeric(precision=6, scale=2),
            nullable=True,
        ),
        sa.Column(
            "casual_leaves_taken", sa.Numeric(precision=6, scale=2), nullable=True
        ),
        sa.Column(
            "casual_leaves_half_day_taken",
            sa.Numeric(precision=6, scale=2),
            nullable=True,
        ),
        sa.Column("sick_leaves_taken", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column(
            "privilege_leaves_taken", sa.Numeric(precision=6, scale=2), nullable=True
        ),
        sa.Column(
            "restricted_holidays_taken", sa.Numeric(precision=6, scale=2), nullable=True
        ),
        sa.Column(
            "joining_leave_taken", sa.Numeric(precision=6, scale=2), nullable=True
        ),
        sa.Column("lop_taken", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("strike_taken", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column(
            "special_leave_taken", sa.Numeric(precision=6, scale=2), nullable=True
        ),
        sa.Column(
            "maternity_leave_taken", sa.Numeric(precision=6, scale=2), nullable=True
        ),
        sa.Column(
            "paternity_leave_taken", sa.Numeric(precision=6, scale=2), nullable=True
        ),
        sa.Column(
            "leave_encashment_days", sa.Numeric(precision=6, scale=2), nullable=True
        ),
        sa.Column("leave_encashment_block_year", sa.String(), nullable=True),
        sa.Column("date_of_leave_encashment", sa.Date(), nullable=True),
        sa.Column("opening_balance_date", sa.Date(), nullable=True),
        sa.Column("closing_balance_date", sa.Date(), nullable=True),
        sa.Column("current_status", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leave_balance")),
    )
    op.create_table(
        "leave_submission_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("leaves_submitted_to_est_dept", sa.Date(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leave_submission_data")),
    )
    op.create_table(
        "public_holiday",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_of_holiday", sa.Date(), nullable=True),
        sa.Column("name_of_holiday", sa.String(), nullable=True),
        sa.Column("type_of_holiday", sa.String(), nullable=True),
        sa.Column("type_of_list", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_public_holiday")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("public_holiday")
    op.drop_table("leave_submission_data")
    op.drop_table("leave_balance")
    op.drop_table("leave_application")
    op.drop_table("employee_data")
    op.drop_table("attendance_register")
    # ### end Alembic commands ###
