"""empty message

Revision ID: 82936fc825bf
Revises: c118e6549103
Create Date: 2024-07-26 11:31:40.604494

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "82936fc825bf"
down_revision = "c118e6549103"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recon_update_balance", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("ro_balance", sa.Numeric(precision=20, scale=2), nullable=True)
        )
        batch_op.add_column(sa.Column("ro_dr_cr", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("ho_dr_cr", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recon_update_balance", schema=None) as batch_op:
        batch_op.drop_column("ho_dr_cr")
        batch_op.drop_column("ro_dr_cr")
        batch_op.drop_column("ro_balance")

    # ### end Alembic commands ###
