"""empty message

Revision ID: 8e712256f045
Revises: a364c0701ec4
Create Date: 2024-09-24 11:48:43.315717

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8e712256f045"
down_revision = "a364c0701ec4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("coinsurance", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_by", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("date_created_date", sa.DateTime(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("coinsurance", schema=None) as batch_op:
        batch_op.drop_column("date_created_date")
        batch_op.drop_column("created_by")

    # ### end Alembic commands ###
