"""empty message

Revision ID: 90e8789e9946
Revises: c22587616ab7
Create Date: 2025-07-07 12:04:24.839816

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "90e8789e9946"
down_revision = "c22587616ab7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("coinsurance_token_request_id", schema=None) as batch_op:
        batch_op.add_column(sa.Column("jv_gl_code", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("jv_sl_code", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("jv_passed", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("coinsurance_token_request_id", schema=None) as batch_op:
        batch_op.drop_column("jv_passed")
        batch_op.drop_column("jv_sl_code")
        batch_op.drop_column("jv_gl_code")

    # ### end Alembic commands ###
