"""empty message

Revision ID: 970b0de246bb
Revises: 6488aa5c39fb
Create Date: 2024-12-17 18:11:11.698628

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "970b0de246bb"
down_revision = "6488aa5c39fb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("coinsurance", schema=None) as batch_op:
        batch_op.alter_column(
            "payable_amount",
            existing_type=sa.INTEGER(),
            type_=sa.Numeric(precision=15, scale=2),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "receivable_amount",
            existing_type=sa.INTEGER(),
            type_=sa.Numeric(precision=15, scale=2),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "int_ri_payable_amount",
            existing_type=sa.INTEGER(),
            type_=sa.Numeric(precision=15, scale=2),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "int_ri_receivable_amount",
            existing_type=sa.INTEGER(),
            type_=sa.Numeric(precision=15, scale=2),
            existing_nullable=True,
        )
        batch_op.drop_column("net_amount")

    with op.batch_alter_table("coinsurance_log", schema=None) as batch_op:
        batch_op.add_column(sa.Column("insured_name", sa.String(), nullable=True))
        batch_op.alter_column(
            "payable_amount",
            existing_type=sa.INTEGER(),
            type_=sa.Numeric(precision=15, scale=2),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "receivable_amount",
            existing_type=sa.INTEGER(),
            type_=sa.Numeric(precision=15, scale=2),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "int_ri_payable_amount",
            existing_type=sa.INTEGER(),
            type_=sa.Numeric(precision=15, scale=2),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "int_ri_receivable_amount",
            existing_type=sa.INTEGER(),
            type_=sa.Numeric(precision=15, scale=2),
            existing_nullable=True,
        )
        batch_op.drop_column("net_amount")

    with op.batch_alter_table("settlement", schema=None) as batch_op:
        batch_op.alter_column(
            "settled_amount",
            existing_type=sa.INTEGER(),
            type_=sa.Numeric(precision=15, scale=2),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settlement", schema=None) as batch_op:
        batch_op.alter_column(
            "settled_amount",
            existing_type=sa.Numeric(precision=15, scale=2),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )

    with op.batch_alter_table("coinsurance_log", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("net_amount", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.alter_column(
            "int_ri_receivable_amount",
            existing_type=sa.Numeric(precision=15, scale=2),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "int_ri_payable_amount",
            existing_type=sa.Numeric(precision=15, scale=2),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "receivable_amount",
            existing_type=sa.Numeric(precision=15, scale=2),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "payable_amount",
            existing_type=sa.Numeric(precision=15, scale=2),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
        batch_op.drop_column("insured_name")

    with op.batch_alter_table("coinsurance", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("net_amount", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.alter_column(
            "int_ri_receivable_amount",
            existing_type=sa.Numeric(precision=15, scale=2),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "int_ri_payable_amount",
            existing_type=sa.Numeric(precision=15, scale=2),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "receivable_amount",
            existing_type=sa.Numeric(precision=15, scale=2),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "payable_amount",
            existing_type=sa.Numeric(precision=15, scale=2),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
