"""PG tieups: Add new columns in models

Revision ID: 9ff332adc359
Revises: 045313e07f72
Create Date: 2026-04-29 20:38:55.169063

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9ff332adc359"
down_revision = "045313e07f72"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payment_gateway_tieup", schema=None) as batch_op:
        batch_op.add_column(sa.Column("gl_code", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("bank_code", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("bank_branch_code", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payment_gateway_tieup", schema=None) as batch_op:
        batch_op.drop_column("bank_branch_code")
        batch_op.drop_column("bank_code")
        batch_op.drop_column("gl_code")

    # ### end Alembic commands ###
