"""empty message

Revision ID: a0cde34b0fad
Revises: 18070708dcf2
Create Date: 2024-07-02 15:52:19.454418

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a0cde34b0fad"
down_revision = "18070708dcf2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "head_office_accounts_tracker",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("str_work", sa.String(), nullable=True),
        sa.Column("str_period", sa.String(), nullable=True),
        sa.Column("str_person", sa.String(), nullable=True),
        sa.Column("bool_current_status", sa.Boolean(), nullable=True),
        sa.Column("text_remarks", sa.Text(), nullable=True),
        sa.Column("date_created_date", sa.DateTime(), nullable=True),
        sa.Column("date_updated_date", sa.DateTime(), nullable=True),
        sa.Column("date_deleted_date", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_head_office_accounts_tracker")),
    )
    op.create_table(
        "head_office_bank_recon_tracker",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("str_period", sa.String(), nullable=True),
        sa.Column("str_name_of_bank", sa.String(), nullable=True),
        sa.Column("str_bank_address", sa.String(), nullable=True),
        sa.Column("str_purpose", sa.String(), nullable=True),
        sa.Column("str_person", sa.String(), nullable=True),
        sa.Column("str_gl_code", sa.String(), nullable=True),
        sa.Column("str_sl_code", sa.String(), nullable=True),
        sa.Column("str_bank_account_number", sa.String(), nullable=True),
        sa.Column("str_customer_id", sa.String(), nullable=True),
        sa.Column("boolean_mis_shared", sa.Boolean(), nullable=True),
        sa.Column("str_brs_file_upload", sa.String(), nullable=True),
        sa.Column("boolean_jv_passed", sa.Boolean(), nullable=True),
        sa.Column("str_bank_confirmation_file_upload", sa.String(), nullable=True),
        sa.Column("text_remarks", sa.Text(), nullable=True),
        sa.Column("date_created_date", sa.DateTime(), nullable=True),
        sa.Column("date_updated_date", sa.DateTime(), nullable=True),
        sa.Column("date_deleted_date", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_head_office_bank_recon_tracker")),
    )
    op.create_table(
        "bank_recon_excess_credit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("brs_month_id", sa.Integer(), nullable=True),
        sa.Column("instrument_number", sa.String(), nullable=True),
        sa.Column(
            "instrument_amount", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column("date_of_instrument", sa.Date(), nullable=True),
        sa.Column("date_of_collection", sa.Date(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["brs_month_id"],
            ["brs_month.id"],
            name=op.f("fk_bank_recon_excess_credit_brs_month_id_brs_month"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_recon_excess_credit")),
    )
    op.create_table(
        "bank_recon_short_credit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("brs_month_id", sa.Integer(), nullable=True),
        sa.Column("instrument_number", sa.String(), nullable=True),
        sa.Column(
            "instrument_amount", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column("date_of_instrument", sa.Date(), nullable=True),
        sa.Column("date_of_collection", sa.Date(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["brs_month_id"],
            ["brs_month.id"],
            name=op.f("fk_bank_recon_short_credit_brs_month_id_brs_month"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_recon_short_credit")),
    )
    with op.batch_alter_table("brs_month", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "int_deposited_not_credited",
                sa.Numeric(precision=15, scale=2),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "int_short_credited", sa.Numeric(precision=15, scale=2), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "int_excess_credited", sa.Numeric(precision=15, scale=2), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "int_balance_as_per_bank",
                sa.Numeric(precision=15, scale=2),
                nullable=True,
            )
        )
        batch_op.drop_column("file_outstanding_entries")

    with op.batch_alter_table("outstanding", schema=None) as batch_op:
        batch_op.add_column(sa.Column("remarks", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outstanding", schema=None) as batch_op:
        batch_op.drop_column("remarks")

    with op.batch_alter_table("brs_month", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "file_outstanding_entries",
                sa.VARCHAR(),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.drop_column("int_balance_as_per_bank")
        batch_op.drop_column("int_excess_credited")
        batch_op.drop_column("int_short_credited")
        batch_op.drop_column("int_deposited_not_credited")

    op.drop_table("bank_recon_short_credit")
    op.drop_table("bank_recon_excess_credit")
    op.drop_table("head_office_bank_recon_tracker")
    op.drop_table("head_office_accounts_tracker")
    # ### end Alembic commands ###
