"""empty message

Revision ID: a364c0701ec4
Revises: 4acbc523056a
Create Date: 2024-09-23 12:20:23.199561

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a364c0701ec4"
down_revision = "4acbc523056a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budget_allocation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("str_financial_year", sa.String(), nullable=True),
        sa.Column("str_type", sa.String(), nullable=True),
        sa.Column("str_ro_code", sa.String(), nullable=True),
        sa.Column("str_expense_head", sa.String(), nullable=True),
        sa.Column(
            "int_budget_allocated", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column("current_status", sa.String(), nullable=True),
        sa.Column("date_created_date", sa.DateTime(), nullable=True),
        sa.Column("date_updated_date", sa.DateTime(), nullable=True),
        sa.Column("date_deleted_date", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budget_allocation")),
    )
    op.create_table(
        "budget_utilization",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("str_financial_year", sa.String(), nullable=True),
        sa.Column("str_quarter", sa.String(), nullable=True),
        sa.Column("str_ro_code", sa.String(), nullable=True),
        sa.Column("str_expense_head", sa.String(), nullable=True),
        sa.Column(
            "int_budget_utilized", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column("current_status", sa.String(), nullable=True),
        sa.Column("date_created_date", sa.DateTime(), nullable=True),
        sa.Column("date_updated_date", sa.DateTime(), nullable=True),
        sa.Column("date_deleted_date", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budget_utilization")),
    )
    op.create_table(
        "payment_gateway_tieup",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name_of_head_office_department", sa.String(), nullable=True),
        sa.Column(
            "date_of_request_from_head_office_department", sa.Date(), nullable=True
        ),
        sa.Column("name_of_tieup_partner", sa.String(), nullable=True),
        sa.Column("similar_request_from_other_department", sa.Boolean(), nullable=True),
        sa.Column("nodal_office_agree_for_pg_vender", sa.Boolean(), nullable=True),
        sa.Column("mou_validity_date", sa.Date(), nullable=True),
        sa.Column("ro_code", sa.String(), nullable=True),
        sa.Column("nodal_office_code", sa.String(), nullable=True),
        sa.Column("nodal_office_name", sa.String(), nullable=True),
        sa.Column("tieup_partner_id_for_bank_mandate", sa.String(), nullable=True),
        sa.Column("date_informed_to_bank_for_bank_mandate", sa.Date(), nullable=True),
        sa.Column(
            "date_of_receipt_of_bank_mandate_with_bank_seal", sa.Date(), nullable=True
        ),
        sa.Column("date_bank_mandate_shared_with_pg_vendor", sa.Date(), nullable=True),
        sa.Column("mid_or_similar_id_as_per_pg_vendor", sa.String(), nullable=True),
        sa.Column("old_mid_name", sa.String(), nullable=True),
        sa.Column("date_of_receipt_of_staging_details", sa.Date(), nullable=True),
        sa.Column(
            "date_of_sharing_staging_details_to_head_office_dept",
            sa.Date(),
            nullable=True,
        ),
        sa.Column("staging_details", sa.String(), nullable=True),
        sa.Column("date_of_receipt_of_production_details", sa.Date(), nullable=True),
        sa.Column("production_details", sa.String(), nullable=True),
        sa.Column(
            "bank_account_details_where_credit_is_expected", sa.String(), nullable=True
        ),
        sa.Column("bank_name", sa.String(), nullable=True),
        sa.Column("bank_account_number", sa.String(), nullable=True),
        sa.Column("whether_t_plus_one_transfer_happening", sa.Boolean(), nullable=True),
        sa.Column("brs_done_upto", sa.Date(), nullable=True),
        sa.Column("spoc_name", sa.String(), nullable=True),
        sa.Column("spoc_employee_number", sa.String(), nullable=True),
        sa.Column("ro_spoc_email_address", sa.String(), nullable=True),
        sa.Column("nodal_office_spoc_email_address", sa.String(), nullable=True),
        sa.Column("nodal_office_gst_address", sa.String(), nullable=True),
        sa.Column(
            "date_of_bank_charges_jv_passed_to_nodal_office", sa.Date(), nullable=True
        ),
        sa.Column("current_status", sa.String(), nullable=True),
        sa.Column("date_created_date", sa.DateTime(), nullable=True),
        sa.Column("date_updated_date", sa.DateTime(), nullable=True),
        sa.Column("date_deleted_date", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_gateway_tieup")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment_gateway_tieup")
    op.drop_table("budget_utilization")
    op.drop_table("budget_allocation")
    # ### end Alembic commands ###
