"""empty message

Revision ID: b05919fda2ee
Revises: c807b5a98150
Create Date: 2025-11-18 11:19:05.711281

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b05919fda2ee"
down_revision = "c807b5a98150"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "fund_amount_given_to_investment", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "date_given_to_investment", existing_type=sa.DATE(), nullable=False
        )
        batch_op.alter_column(
            "float_amount_given_to_investment",
            existing_type=sa.NUMERIC(precision=20, scale=2),
            nullable=False,
        )

    with op.batch_alter_table("fund_bank_account_numbers", schema=None) as batch_op:
        batch_op.alter_column(
            "outflow_description", existing_type=sa.VARCHAR(), nullable=False
        )

    with op.batch_alter_table("fund_bank_statement", schema=None) as batch_op:
        batch_op.alter_column(
            "date_uploaded_date", existing_type=sa.DATE(), nullable=False
        )
        batch_op.alter_column("description", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column(
            "flag_description", existing_type=sa.TEXT(), nullable=False
        )

    with op.batch_alter_table("fund_daily_outflow", schema=None) as batch_op:
        batch_op.alter_column("outflow_date", existing_type=sa.DATE(), nullable=False)
        batch_op.alter_column(
            "outflow_amount",
            existing_type=sa.NUMERIC(precision=20, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "outflow_description", existing_type=sa.VARCHAR(), nullable=False
        )

    with op.batch_alter_table("fund_daily_sheet", schema=None) as batch_op:
        batch_op.alter_column(
            "date_current_date", existing_type=sa.DATE(), nullable=False
        )

    with op.batch_alter_table("fund_flag_sheet", schema=None) as batch_op:
        batch_op.alter_column(
            "flag_description", existing_type=sa.TEXT(), nullable=False
        )
        batch_op.alter_column("flag_reg_exp", existing_type=sa.TEXT(), nullable=False)

    with op.batch_alter_table(
        "fund_journal_voucher_flag_sheet", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "txt_description", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("txt_flag", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("txt_gl_code", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("txt_sl_code", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table("fund_major_outgo", schema=None) as batch_op:
        batch_op.alter_column("date_of_outgo", existing_type=sa.DATE(), nullable=False)
        batch_op.alter_column(
            "float_expected_outgo",
            existing_type=sa.NUMERIC(precision=20, scale=2),
            nullable=False,
        )
        batch_op.alter_column("text_dept", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column("text_remarks", existing_type=sa.TEXT(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fund_major_outgo", schema=None) as batch_op:
        batch_op.alter_column("text_remarks", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("text_dept", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column(
            "float_expected_outgo",
            existing_type=sa.NUMERIC(precision=20, scale=2),
            nullable=True,
        )
        batch_op.alter_column("date_of_outgo", existing_type=sa.DATE(), nullable=True)

    with op.batch_alter_table(
        "fund_journal_voucher_flag_sheet", schema=None
    ) as batch_op:
        batch_op.alter_column("txt_sl_code", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("txt_gl_code", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("txt_flag", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "txt_description", existing_type=sa.VARCHAR(), nullable=True
        )

    with op.batch_alter_table("fund_flag_sheet", schema=None) as batch_op:
        batch_op.alter_column("flag_reg_exp", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column(
            "flag_description", existing_type=sa.TEXT(), nullable=True
        )

    with op.batch_alter_table("fund_daily_sheet", schema=None) as batch_op:
        batch_op.alter_column(
            "date_current_date", existing_type=sa.DATE(), nullable=True
        )

    with op.batch_alter_table("fund_daily_outflow", schema=None) as batch_op:
        batch_op.alter_column(
            "outflow_description", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "outflow_amount",
            existing_type=sa.NUMERIC(precision=20, scale=2),
            nullable=True,
        )
        batch_op.alter_column("outflow_date", existing_type=sa.DATE(), nullable=True)

    with op.batch_alter_table("fund_bank_statement", schema=None) as batch_op:
        batch_op.alter_column(
            "flag_description", existing_type=sa.TEXT(), nullable=True
        )
        batch_op.alter_column("description", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column(
            "date_uploaded_date", existing_type=sa.DATE(), nullable=True
        )

    with op.batch_alter_table("fund_bank_account_numbers", schema=None) as batch_op:
        batch_op.alter_column(
            "outflow_description", existing_type=sa.VARCHAR(), nullable=True
        )

    with op.batch_alter_table(
        "fund_amount_given_to_investment", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "float_amount_given_to_investment",
            existing_type=sa.NUMERIC(precision=20, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "date_given_to_investment", existing_type=sa.DATE(), nullable=True
        )

    # ### end Alembic commands ###
