"""empty message

Revision ID: b4deff02a197
Revises: 014ba9cd9efd
Create Date: 2025-11-10 11:34:03.429005

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b4deff02a197"
down_revision = "014ba9cd9efd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lien", schema=None) as batch_op:
        batch_op.alter_column(
            "is_duplicate", existing_type=sa.BOOLEAN(), nullable=False
        )

    with op.batch_alter_table("pool_credits", schema=None) as batch_op:
        batch_op.alter_column(
            "date_uploaded_date", existing_type=sa.DATE(), nullable=False
        )
        batch_op.alter_column("book_date", existing_type=sa.DATE(), nullable=False)
        batch_op.alter_column("description", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column("value_date", existing_type=sa.DATE(), nullable=False)
        batch_op.alter_column(
            "transaction_branch", existing_type=sa.TEXT(), nullable=False
        )
        batch_op.alter_column(
            "flag_description", existing_type=sa.TEXT(), nullable=False
        )

    with op.batch_alter_table("pool_credits_journal_voucher", schema=None) as batch_op:
        batch_op.alter_column(
            "str_regional_office_code", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("gl_code", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("sl_code", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table("pool_credits_portal", schema=None) as batch_op:
        batch_op.alter_column(
            "txt_reference_number", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "date_value_date", existing_type=sa.DATE(), nullable=False
        )
        batch_op.alter_column(
            "amount_credit",
            existing_type=sa.NUMERIC(precision=20, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "txt_name_of_remitter", existing_type=sa.VARCHAR(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pool_credits_portal", schema=None) as batch_op:
        batch_op.alter_column(
            "txt_name_of_remitter", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "amount_credit",
            existing_type=sa.NUMERIC(precision=20, scale=2),
            nullable=True,
        )
        batch_op.alter_column("date_value_date", existing_type=sa.DATE(), nullable=True)
        batch_op.alter_column(
            "txt_reference_number", existing_type=sa.VARCHAR(), nullable=True
        )

    with op.batch_alter_table("pool_credits_journal_voucher", schema=None) as batch_op:
        batch_op.alter_column("sl_code", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("gl_code", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "str_regional_office_code", existing_type=sa.VARCHAR(), nullable=True
        )

    with op.batch_alter_table("pool_credits", schema=None) as batch_op:
        batch_op.alter_column(
            "flag_description", existing_type=sa.TEXT(), nullable=True
        )
        batch_op.alter_column(
            "transaction_branch", existing_type=sa.TEXT(), nullable=True
        )
        batch_op.alter_column("value_date", existing_type=sa.DATE(), nullable=True)
        batch_op.alter_column("description", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("book_date", existing_type=sa.DATE(), nullable=True)
        batch_op.alter_column(
            "date_uploaded_date", existing_type=sa.DATE(), nullable=True
        )

    with op.batch_alter_table("lien", schema=None) as batch_op:
        batch_op.alter_column("is_duplicate", existing_type=sa.BOOLEAN(), nullable=True)

    # ### end Alembic commands ###
