"""empty message

Revision ID: b6eba0e85c81
Revises: f62231c3621f
Create Date: 2025-04-29 12:17:36.771509

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b6eba0e85c81"
down_revision = "f62231c3621f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "centralised_cheque_enable_delete",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_of_month", sa.Date(), nullable=True),
        sa.Column("enable_delete", sa.Boolean(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_centralised_cheque_enable_delete")),
    )
    op.create_table(
        "centralised_cheque_summary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("regional_office_code", sa.String(), nullable=True),
        sa.Column("operating_office_code", sa.String(), nullable=True),
        sa.Column("date_of_month", sa.Date(), nullable=True),
        sa.Column("centralised_cheque_bank", sa.String(), nullable=True),
        sa.Column("centralised_cheque_brs_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_centralised_cheque_summary")),
    )
    op.create_table(
        "centralised_cheque_details",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("summary_id", sa.Integer(), nullable=True),
        sa.Column(
            "opening_balance_unencashed",
            sa.Numeric(precision=15, scale=2),
            nullable=True,
        ),
        sa.Column("cheques_issued", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column(
            "cheques_reissued_unencashed",
            sa.Numeric(precision=15, scale=2),
            nullable=True,
        ),
        sa.Column(
            "opening_balance_stale", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column(
            "cheques_reissued_stale", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column("cheques_cleared", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column(
            "cheques_cancelled", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column(
            "closing_balance_unencashed",
            sa.Numeric(precision=15, scale=2),
            nullable=True,
        ),
        sa.Column(
            "closing_balance_stale", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("prepared_by_employee_name", sa.String(), nullable=True),
        sa.Column("prepared_by_employee_number", sa.String(), nullable=True),
        sa.Column("brs_status", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["summary_id"],
            ["centralised_cheque_summary.id"],
            name=op.f(
                "fk_centralised_cheque_details_summary_id_centralised_cheque_summary"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_centralised_cheque_details")),
    )
    op.create_table(
        "centralised_cheque_instrument_stale_details",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("voucher_number", sa.String(), nullable=True),
        sa.Column("voucher_date", sa.Date(), nullable=True),
        sa.Column("transaction_id", sa.String(), nullable=True),
        sa.Column("instrument_number", sa.String(), nullable=True),
        sa.Column("instrument_date", sa.Date(), nullable=True),
        sa.Column(
            "instrument_amount", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column("payee_name", sa.String(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("instrument_status", sa.String(), nullable=True),
        sa.Column("centralised_cheque_details_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["centralised_cheque_details_id"],
            ["centralised_cheque_details.id"],
            name=op.f(
                "fk_centralised_cheque_instrument_stale_details_centralised_cheque_details_id_centralised_cheque_details"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_centralised_cheque_instrument_stale_details")
        ),
    )
    op.create_table(
        "centralised_cheque_instrument_unencashed_details",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("voucher_number", sa.String(), nullable=True),
        sa.Column("voucher_date", sa.Date(), nullable=True),
        sa.Column("transaction_id", sa.String(), nullable=True),
        sa.Column("instrument_number", sa.String(), nullable=True),
        sa.Column("instrument_date", sa.Date(), nullable=True),
        sa.Column(
            "instrument_amount", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column("payee_name", sa.String(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("instrument_status", sa.String(), nullable=True),
        sa.Column("centralised_cheque_details_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["centralised_cheque_details_id"],
            ["centralised_cheque_details.id"],
            name=op.f(
                "fk_centralised_cheque_instrument_unencashed_details_centralised_cheque_details_id_centralised_cheque_details"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_centralised_cheque_instrument_unencashed_details")
        ),
    )
    with op.batch_alter_table("lien", schema=None) as batch_op:
        batch_op.add_column(sa.Column("bank_remarks", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lien", schema=None) as batch_op:
        batch_op.drop_column("bank_remarks")

    op.drop_table("centralised_cheque_instrument_unencashed_details")
    op.drop_table("centralised_cheque_instrument_stale_details")
    op.drop_table("centralised_cheque_details")
    op.drop_table("centralised_cheque_summary")
    op.drop_table("centralised_cheque_enable_delete")
    # ### end Alembic commands ###
