"""Funds: Rename FundJVflagsheet model column names

Revision ID: bee3031e55ac
Revises: fc0ba4b66f7f
Create Date: 2026-06-01 21:09:41.912282

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "bee3031e55ac"
down_revision = "fc0ba4b66f7f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "fund_journal_voucher_flag_sheet", schema=None
    ) as batch_op:
        batch_op.alter_column("txt_flag", new_column_name="pattern_name")
        batch_op.alter_column("txt_description", new_column_name="pattern")
        batch_op.alter_column("txt_sl_code", new_column_name="sl_code")
        batch_op.alter_column("txt_gl_code", new_column_name="gl_code")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "fund_journal_voucher_flag_sheet", schema=None
    ) as batch_op:
        batch_op.alter_column("sl_code", new_column_name="txt_sl_code")
        batch_op.alter_column("gl_code", new_column_name="txt_gl_code")
        batch_op.alter_column("pattern", new_column_name="txt_description")
        batch_op.alter_column("pattern_name", new_column_name="txt_flag")

    # ### end Alembic commands ###
