"""empty message

Revision ID: c118e6549103
Revises: 10fd113afe4a
Create Date: 2024-07-23 10:51:21.996204

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c118e6549103"
down_revision = "10fd113afe4a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recon_update_balance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("str_period", sa.String(), nullable=True),
        sa.Column("str_regional_office_code", sa.String(), nullable=True),
        sa.Column("ho_balance", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recon_update_balance")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recon_update_balance")
    # ### end Alembic commands ###
