"""empty message

Revision ID: c1370e5faa5a
Revises: d938996e7e62
Create Date: 2025-09-03 11:29:29.593755

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c1370e5faa5a"
down_revision = "d938996e7e62"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lien_version",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("bank_name", sa.String(), autoincrement=False, nullable=True),
        sa.Column("account_number", sa.String(), autoincrement=False, nullable=True),
        sa.Column("ro_name", sa.String(), autoincrement=False, nullable=True),
        sa.Column("ro_code", sa.String(), autoincrement=False, nullable=True),
        sa.Column(
            "lien_amount",
            sa.Numeric(precision=15, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("lien_date", sa.Date(), autoincrement=False, nullable=True),
        sa.Column("court_order_lien", sa.String(), autoincrement=False, nullable=True),
        sa.Column(
            "dd_amount",
            sa.Numeric(precision=15, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("dd_date", sa.Date(), autoincrement=False, nullable=True),
        sa.Column("court_order_dd", sa.String(), autoincrement=False, nullable=True),
        sa.Column("bank_remarks", sa.Text(), autoincrement=False, nullable=True),
        sa.Column(
            "action_taken_by_banker", sa.Text(), autoincrement=False, nullable=True
        ),
        sa.Column("department", sa.String(), autoincrement=False, nullable=True),
        sa.Column("court_name", sa.String(), autoincrement=False, nullable=True),
        sa.Column("case_number", sa.String(), autoincrement=False, nullable=True),
        sa.Column("case_title", sa.String(), autoincrement=False, nullable=True),
        sa.Column("mact_number", sa.String(), autoincrement=False, nullable=True),
        sa.Column("petitioner_name", sa.String(), autoincrement=False, nullable=True),
        sa.Column("date_of_lien_order", sa.Date(), autoincrement=False, nullable=True),
        sa.Column(
            "claim_already_paid_by_hub_office",
            sa.String(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("claim_number", sa.String(), autoincrement=False, nullable=True),
        sa.Column(
            "date_of_claim_registration", sa.Date(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "claim_disbursement_voucher",
            sa.String(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "lien_dd_reversal_order", sa.String(), autoincrement=False, nullable=True
        ),
        sa.Column("lien_status", sa.String(), autoincrement=False, nullable=True),
        sa.Column("appeal_given", sa.String(), autoincrement=False, nullable=True),
        sa.Column("appeal_copy", sa.String(), autoincrement=False, nullable=True),
        sa.Column("appeal_given_2", sa.String(), autoincrement=False, nullable=True),
        sa.Column("appeal_copy_2", sa.String(), autoincrement=False, nullable=True),
        sa.Column("stay_obtained", sa.String(), autoincrement=False, nullable=True),
        sa.Column("stay_order", sa.String(), autoincrement=False, nullable=True),
        sa.Column(
            "claim_accounting_voucher_number",
            sa.String(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "claim_accounting_voucher_date",
            sa.Date(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("ro_remarks", sa.Text(), autoincrement=False, nullable=True),
        sa.Column("ho_tp_remarks", sa.Text(), autoincrement=False, nullable=True),
        sa.Column(
            "court_order_lien_reversal", sa.String(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "court_order_dd_reversal", sa.String(), autoincrement=False, nullable=True
        ),
        sa.Column("created_by", sa.String(), autoincrement=False, nullable=True),
        sa.Column("created_on", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated_by", sa.String(), autoincrement=False, nullable=True),
        sa.Column("updated_on", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("is_duplicate", sa.Boolean(), autoincrement=False, nullable=True),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id", name=op.f("pk_lien_version")),
    )
    with op.batch_alter_table("lien_version", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lien_version_end_transaction_id"),
            ["end_transaction_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_lien_version_operation_type"),
            ["operation_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_lien_version_transaction_id"),
            ["transaction_id"],
            unique=False,
        )

    op.create_table(
        "transaction",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("remote_addr", sa.String(length=50), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("issued_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_transaction_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transaction")),
    )
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_transaction_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("lien", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mact_number", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("appeal_given_2", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("appeal_copy_2", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("is_duplicate", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lien", schema=None) as batch_op:
        batch_op.drop_column("is_duplicate")
        batch_op.drop_column("appeal_copy_2")
        batch_op.drop_column("appeal_given_2")
        batch_op.drop_column("mact_number")

    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transaction_user_id"))

    op.drop_table("transaction")
    with op.batch_alter_table("lien_version", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lien_version_transaction_id"))
        batch_op.drop_index(batch_op.f("ix_lien_version_operation_type"))
        batch_op.drop_index(batch_op.f("ix_lien_version_end_transaction_id"))

    op.drop_table("lien_version")
    # ### end Alembic commands ###
