"""empty message

Revision ID: c22587616ab7
Revises: 625ad2328c2a
Create Date: 2025-06-16 10:56:55.944243

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c22587616ab7"
down_revision = "625ad2328c2a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payment_gateway_tieup", schema=None) as batch_op:
        batch_op.add_column(sa.Column("bank_mandate_file", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payment_gateway_tieup", schema=None) as batch_op:
        batch_op.drop_column("bank_mandate_file")

    # ### end Alembic commands ###
