"""empty message

Revision ID: c3d62f8d6013
Revises: 1e0fcdb3e358
Create Date: 2024-07-12 15:09:49.215675

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c3d62f8d6013"
down_revision = "1e0fcdb3e358"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recon_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("str_period", sa.String(), nullable=True),
        sa.Column("str_regional_office_code", sa.String(), nullable=True),
        sa.Column("str_department", sa.String(), nullable=True),
        sa.Column("str_target_ro_code", sa.String(), nullable=True),
        sa.Column("txt_remarks", sa.Text(), nullable=True),
        sa.Column("str_debit_credit", sa.String(), nullable=True),
        sa.Column("amount_recon", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("str_assigned_to", sa.String(), nullable=True),
        sa.Column("str_head_office_status", sa.String(), nullable=True),
        sa.Column("txt_head_office_remarks", sa.Text(), nullable=True),
        sa.Column("str_head_office_voucher", sa.String(), nullable=True),
        sa.Column("date_head_office_voucher", sa.Date(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("date_created_date", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("date_updated_date", sa.DateTime(), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.Column("date_deleted_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recon_entries")),
    )
    op.create_table(
        "recon_summary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("str_period", sa.String(), nullable=True),
        sa.Column("str_regional_office_code", sa.String(), nullable=True),
        sa.Column("input_ro_balance_dr_cr", sa.String(), nullable=True),
        sa.Column(
            "input_float_ro_balance", sa.Numeric(precision=20, scale=2), nullable=True
        ),
        sa.Column("input_ho_balance_dr_cr", sa.String(), nullable=True),
        sa.Column(
            "input_float_ho_balance", sa.Numeric(precision=20, scale=2), nullable=True
        ),
        sa.Column("float_ho_balance", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("date_created_date", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("date_updated_date", sa.DateTime(), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.Column("date_deleted_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recon_summary")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recon_summary")
    op.drop_table("recon_entries")
    # ### end Alembic commands ###
