"""RO audit report: Create models

Revision ID: c75401a91e5f
Revises: 6a251427dea0
Create Date: 2026-04-08 21:59:22.550849

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c75401a91e5f"
down_revision = "6a251427dea0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auditor_regional_office_mapping",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("regional_office_code", sa.String(), nullable=False),
        sa.Column("regional_office_name", sa.String(), nullable=False),
        sa.Column("period", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auditor_regional_office_mapping")),
    )
    op.create_table(
        "regional_office_audit_observation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("regional_office_code", sa.String(), nullable=False),
        sa.Column("period", sa.String(), nullable=False),
        sa.Column("department", sa.String(), nullable=False),
        sa.Column("audit_observation", sa.Text(), nullable=False),
        sa.Column("regional_office_remarks", sa.Text(), nullable=False),
        sa.Column("head_office_remarks", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_regional_office_audit_observation")
        ),
    )
    op.create_table(
        "regional_office_audit_report",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("regional_office_code", sa.String(), nullable=False),
        sa.Column("regional_office_name", sa.String(), nullable=False),
        sa.Column("period", sa.String(), nullable=False),
        sa.Column("audit_report", sa.String(), nullable=True),
        sa.Column("annexures", sa.String(), nullable=True),
        sa.Column("notes_forming_part_of_accounts", sa.String(), nullable=True),
        sa.Column("mode_of_dispatch", sa.String(), nullable=True),
        sa.Column("date_of_dispatch", sa.Date(), nullable=True),
        sa.Column("tracking_number", sa.String(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regional_office_audit_report")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("regional_office_audit_report")
    op.drop_table("regional_office_audit_observation")
    op.drop_table("auditor_regional_office_mapping")
    # ### end Alembic commands ###
