"""empty message

Revision ID: c807b5a98150
Revises: b4deff02a197
Create Date: 2025-11-14 18:25:52.751536

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c807b5a98150"
down_revision = "b4deff02a197"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attendance_register", schema=None) as batch_op:
        batch_op.alter_column(
            "date_of_attendance", existing_type=sa.DATE(), nullable=False
        )
        batch_op.alter_column(
            "employee_name", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "employee_number", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "employee_designation", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "date_of_joining_current_cadre", existing_type=sa.DATE(), nullable=False
        )

    with op.batch_alter_table("employee_data", schema=None) as batch_op:
        batch_op.alter_column(
            "employee_name", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "employee_number", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "employee_designation", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "date_of_joining_current_cadre", existing_type=sa.DATE(), nullable=False
        )
        batch_op.alter_column(
            "current_status", existing_type=sa.VARCHAR(), nullable=False
        )

    with op.batch_alter_table("leave_application", schema=None) as batch_op:
        batch_op.alter_column(
            "type_of_leave", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("start_date", existing_type=sa.DATE(), nullable=False)
        batch_op.alter_column("end_date", existing_type=sa.DATE(), nullable=False)
        batch_op.alter_column(
            "number_of_days_leave",
            existing_type=sa.NUMERIC(precision=6, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "number_of_days_off_duty",
            existing_type=sa.NUMERIC(precision=6, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "employee_name", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "employee_number", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "employee_designation", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "available_leave_credit",
            existing_type=sa.NUMERIC(precision=6, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "list_attendance_register_days",
            existing_type=postgresql.ARRAY(sa.INTEGER()),
            nullable=False,
        )
        batch_op.alter_column(
            "current_status", existing_type=sa.VARCHAR(), nullable=False
        )

    with op.batch_alter_table("leave_balance", schema=None) as batch_op:
        batch_op.alter_column(
            "calendar_year", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "employee_name", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "employee_number", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "opening_casual_leave_balance",
            existing_type=sa.NUMERIC(precision=6, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "opening_sick_leave_balance",
            existing_type=sa.NUMERIC(precision=6, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "opening_rh_balance",
            existing_type=sa.NUMERIC(precision=6, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "opening_privileged_leave_balance",
            existing_type=sa.NUMERIC(precision=6, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "current_casual_leave_balance",
            existing_type=sa.NUMERIC(precision=6, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "current_sick_leave_balance",
            existing_type=sa.NUMERIC(precision=6, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "current_rh_balance",
            existing_type=sa.NUMERIC(precision=6, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "opening_balance_date", existing_type=sa.DATE(), nullable=False
        )
        batch_op.alter_column(
            "current_status", existing_type=sa.VARCHAR(), nullable=False
        )

    with op.batch_alter_table("leave_submission_data", schema=None) as batch_op:
        batch_op.alter_column(
            "leaves_submitted_to_est_dept", existing_type=sa.DATE(), nullable=False
        )

    with op.batch_alter_table("public_holiday", schema=None) as batch_op:
        batch_op.alter_column(
            "date_of_holiday", existing_type=sa.DATE(), nullable=False
        )
        batch_op.alter_column(
            "name_of_holiday", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "type_of_holiday", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "type_of_list", existing_type=sa.VARCHAR(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("public_holiday", schema=None) as batch_op:
        batch_op.alter_column("type_of_list", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "type_of_holiday", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "name_of_holiday", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("date_of_holiday", existing_type=sa.DATE(), nullable=True)

    with op.batch_alter_table("leave_submission_data", schema=None) as batch_op:
        batch_op.alter_column(
            "leaves_submitted_to_est_dept", existing_type=sa.DATE(), nullable=True
        )

    with op.batch_alter_table("leave_balance", schema=None) as batch_op:
        batch_op.alter_column(
            "current_status", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "opening_balance_date", existing_type=sa.DATE(), nullable=True
        )
        batch_op.alter_column(
            "current_rh_balance",
            existing_type=sa.NUMERIC(precision=6, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "current_sick_leave_balance",
            existing_type=sa.NUMERIC(precision=6, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "current_casual_leave_balance",
            existing_type=sa.NUMERIC(precision=6, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "opening_privileged_leave_balance",
            existing_type=sa.NUMERIC(precision=6, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "opening_rh_balance",
            existing_type=sa.NUMERIC(precision=6, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "opening_sick_leave_balance",
            existing_type=sa.NUMERIC(precision=6, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "opening_casual_leave_balance",
            existing_type=sa.NUMERIC(precision=6, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "employee_number", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "employee_name", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "calendar_year", existing_type=sa.INTEGER(), nullable=True
        )

    with op.batch_alter_table("leave_application", schema=None) as batch_op:
        batch_op.alter_column(
            "current_status", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "list_attendance_register_days",
            existing_type=postgresql.ARRAY(sa.INTEGER()),
            nullable=True,
        )
        batch_op.alter_column(
            "available_leave_credit",
            existing_type=sa.NUMERIC(precision=6, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "employee_designation", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "employee_number", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "employee_name", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "number_of_days_off_duty",
            existing_type=sa.NUMERIC(precision=6, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "number_of_days_leave",
            existing_type=sa.NUMERIC(precision=6, scale=2),
            nullable=True,
        )
        batch_op.alter_column("end_date", existing_type=sa.DATE(), nullable=True)
        batch_op.alter_column("start_date", existing_type=sa.DATE(), nullable=True)
        batch_op.alter_column(
            "type_of_leave", existing_type=sa.VARCHAR(), nullable=True
        )

    with op.batch_alter_table("employee_data", schema=None) as batch_op:
        batch_op.alter_column(
            "current_status", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "date_of_joining_current_cadre", existing_type=sa.DATE(), nullable=True
        )
        batch_op.alter_column(
            "employee_designation", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "employee_number", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "employee_name", existing_type=sa.VARCHAR(), nullable=True
        )

    with op.batch_alter_table("attendance_register", schema=None) as batch_op:
        batch_op.alter_column(
            "date_of_joining_current_cadre", existing_type=sa.DATE(), nullable=True
        )
        batch_op.alter_column(
            "employee_designation", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "employee_number", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "employee_name", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "date_of_attendance", existing_type=sa.DATE(), nullable=True
        )

    # ### end Alembic commands ###
