"""empty message

Revision ID: cffdc36a0a84
Revises: 64e1008171c0
Create Date: 2025-10-27 12:22:01.133807

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cffdc36a0a84"
down_revision = "64e1008171c0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("announcements", schema=None) as batch_op:
        batch_op.alter_column("txt_title", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column("txt_message", existing_type=sa.TEXT(), nullable=False)

    with op.batch_alter_table("bank_guarantee", schema=None) as batch_op:
        batch_op.alter_column("ro_code", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("oo_code", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "customer_name", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("customer_id", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("payment_id", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "date_of_payment", existing_type=sa.DATE(), nullable=False
        )
        batch_op.alter_column("reason", existing_type=sa.TEXT(), nullable=False)

    with op.batch_alter_table("budget_allocation", schema=None) as batch_op:
        batch_op.alter_column(
            "str_financial_year", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("str_type", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("str_ro_code", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "str_expense_head", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "int_budget_allocated",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )

    with op.batch_alter_table("budget_utilization", schema=None) as batch_op:
        batch_op.alter_column(
            "str_financial_year", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("str_quarter", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("str_ro_code", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "str_expense_head", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "int_budget_utilized",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )

    with op.batch_alter_table("coinsurance_balances", schema=None) as batch_op:
        batch_op.alter_column("str_zone", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "str_regional_office_code", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("office_code", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "company_name", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("period", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "hub_due_to_claims",
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            nullable=False,
        )
        batch_op.alter_column(
            "hub_due_to_premium",
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            nullable=False,
        )
        batch_op.alter_column(
            "hub_due_from_claims",
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            nullable=False,
        )
        batch_op.alter_column(
            "hub_due_from_premium",
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            nullable=False,
        )
        batch_op.alter_column(
            "oo_due_to", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
        )
        batch_op.alter_column(
            "oo_due_from",
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            nullable=False,
        )
        batch_op.alter_column(
            "net_amount",
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            nullable=False,
        )
        batch_op.drop_column("deleted_on")
        batch_op.drop_column("deleted_by")

    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.alter_column("office_code", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("office_name", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "employee_number", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column("zone", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("role", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table("contracts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_by", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("created_on", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("updated_by", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("updated_on", sa.DateTime(), nullable=True))
        batch_op.alter_column("vendor", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("purpose", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("start_date", existing_type=sa.DATE(), nullable=False)
        batch_op.alter_column("end_date", existing_type=sa.DATE(), nullable=False)
        batch_op.alter_column("renewal", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "notice_period", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("remarks", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table("escalation_matrix", schema=None) as batch_op:
        batch_op.alter_column(
            "service_type", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "nature_of_entity", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "name_of_entity", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("level", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("roll", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "email_address", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "contact_number", existing_type=sa.VARCHAR(), nullable=False
        )

    with op.batch_alter_table("head_office_accounts_tracker", schema=None) as batch_op:
        batch_op.alter_column("str_work", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("str_period", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table(
        "head_office_bank_recon_tracker", schema=None
    ) as batch_op:
        batch_op.alter_column("str_period", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table("privilege_leave_balance", schema=None) as batch_op:
        batch_op.alter_column(
            "calendar_year", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "employee_name", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "employee_number", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "employee_designation", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "employee_ro_code", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "employee_oo_code", existing_type=sa.VARCHAR(), nullable=False
        )

    with op.batch_alter_table("sick_leave_balance", schema=None) as batch_op:
        batch_op.alter_column(
            "calendar_year", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "employee_name", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "employee_number", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "employee_designation", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "employee_ro_code", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "employee_oo_code", existing_type=sa.VARCHAR(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sick_leave_balance", schema=None) as batch_op:
        batch_op.alter_column(
            "employee_oo_code", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "employee_ro_code", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "employee_designation", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "employee_number", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "employee_name", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "calendar_year", existing_type=sa.INTEGER(), nullable=True
        )

    with op.batch_alter_table("privilege_leave_balance", schema=None) as batch_op:
        batch_op.alter_column(
            "employee_oo_code", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "employee_ro_code", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "employee_designation", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "employee_number", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "employee_name", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "calendar_year", existing_type=sa.INTEGER(), nullable=True
        )

    with op.batch_alter_table(
        "head_office_bank_recon_tracker", schema=None
    ) as batch_op:
        batch_op.alter_column("str_period", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("head_office_accounts_tracker", schema=None) as batch_op:
        batch_op.alter_column("str_period", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("str_work", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("escalation_matrix", schema=None) as batch_op:
        batch_op.alter_column(
            "contact_number", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "email_address", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("roll", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("level", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "name_of_entity", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "nature_of_entity", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("service_type", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("contracts", schema=None) as batch_op:
        batch_op.alter_column("remarks", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "notice_period", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("renewal", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("end_date", existing_type=sa.DATE(), nullable=True)
        batch_op.alter_column("start_date", existing_type=sa.DATE(), nullable=True)
        batch_op.alter_column("purpose", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("vendor", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.drop_column("updated_on")
        batch_op.drop_column("updated_by")
        batch_op.drop_column("created_on")
        batch_op.drop_column("created_by")

    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.alter_column("role", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("zone", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "employee_number", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("office_name", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("office_code", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("coinsurance_balances", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("deleted_by", sa.VARCHAR(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "deleted_on", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
            )
        )
        batch_op.alter_column(
            "net_amount", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
        )
        batch_op.alter_column(
            "oo_due_from",
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            nullable=True,
        )
        batch_op.alter_column(
            "oo_due_to", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
        )
        batch_op.alter_column(
            "hub_due_from_premium",
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            nullable=True,
        )
        batch_op.alter_column(
            "hub_due_from_claims",
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            nullable=True,
        )
        batch_op.alter_column(
            "hub_due_to_premium",
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            nullable=True,
        )
        batch_op.alter_column(
            "hub_due_to_claims",
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            nullable=True,
        )
        batch_op.alter_column("period", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("company_name", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("office_code", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "str_regional_office_code", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("str_zone", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("budget_utilization", schema=None) as batch_op:
        batch_op.alter_column(
            "int_budget_utilized",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "str_expense_head", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("str_ro_code", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("str_quarter", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "str_financial_year", existing_type=sa.VARCHAR(), nullable=True
        )

    with op.batch_alter_table("budget_allocation", schema=None) as batch_op:
        batch_op.alter_column(
            "int_budget_allocated",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "str_expense_head", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("str_ro_code", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("str_type", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "str_financial_year", existing_type=sa.VARCHAR(), nullable=True
        )

    with op.batch_alter_table("bank_guarantee", schema=None) as batch_op:
        batch_op.alter_column("reason", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("date_of_payment", existing_type=sa.DATE(), nullable=True)
        batch_op.alter_column("payment_id", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("customer_id", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "customer_name", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("oo_code", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("ro_code", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("announcements", schema=None) as batch_op:
        batch_op.alter_column("txt_message", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("txt_title", existing_type=sa.TEXT(), nullable=True)

    # ### end Alembic commands ###
