"""Create BRS tieup models

Revision ID: d51cadc7bc3c
Revises: db840b3ff62f
Create Date: 2026-03-23 21:02:51.476238

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d51cadc7bc3c"
down_revision = "db840b3ff62f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_recon_tieup_summary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("regional_office", sa.String(), nullable=False),
        sa.Column("operating_office", sa.String(), nullable=False),
        sa.Column("month", sa.String(), nullable=False),
        sa.Column("gl_identifier", sa.String(), nullable=False),
        sa.Column("tieup_partner_name", sa.String(), nullable=False),
        sa.Column("tieup_bank_name", sa.String(), nullable=True),
        sa.Column("tieup_bank_account_number", sa.String(), nullable=True),
        sa.Column("tieup_bank_ifsc_code", sa.String(), nullable=True),
        sa.Column("tieup_gc_gl_code", sa.String(), nullable=False),
        sa.Column("tieup_gc_bank_code", sa.String(), nullable=False),
        sa.Column("tieup_gc_branch_code", sa.String(), nullable=False),
        sa.Column("tieup_gc_bank_name", sa.String(), nullable=False),
        sa.Column("tieup_bank_branch_name", sa.String(), nullable=True),
        sa.Column("tieup_bank_branch_address", sa.String(), nullable=True),
        sa.Column("tieup_brs_month_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_recon_tieup_summary")),
    )
    op.create_table(
        "bank_recon_tieup_details",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("brs_id", sa.Integer(), nullable=False),
        sa.Column("opening_balance", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("opening_on_hand", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("transactions", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("cancellations", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("fund_transfer", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("bank_charges", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("closing_on_hand", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("closing_balance", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column(
            "deposited_not_credited", sa.Numeric(precision=15, scale=2), nullable=False
        ),
        sa.Column("short_credited", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("excess_credited", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column(
            "balance_as_per_bank", sa.Numeric(precision=15, scale=2), nullable=False
        ),
        sa.Column("bank_statement", sa.String(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("prepared_by_employee_name", sa.String(), nullable=False),
        sa.Column("prepared_by_employee_number", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["brs_id"],
            ["bank_recon_tieup_summary.id"],
            name=op.f("fk_bank_recon_tieup_details_brs_id_bank_recon_tieup_summary"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_recon_tieup_details")),
    )
    op.create_table(
        "bank_recon_tieup_excess_credit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("brs_details_id", sa.Integer(), nullable=False),
        sa.Column("mode_of_collection", sa.String(), nullable=False),
        sa.Column("instrument_number", sa.String(), nullable=True),
        sa.Column(
            "instrument_amount", sa.Numeric(precision=15, scale=2), nullable=False
        ),
        sa.Column("date_of_instrument", sa.Date(), nullable=True),
        sa.Column("date_of_collection", sa.Date(), nullable=False),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["brs_details_id"],
            ["bank_recon_tieup_details.id"],
            name=op.f(
                "fk_bank_recon_tieup_excess_credit_brs_details_id_bank_recon_tieup_details"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_recon_tieup_excess_credit")),
    )
    op.create_table(
        "bank_recon_tieup_outstanding",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("brs_details_id", sa.Integer(), nullable=False),
        sa.Column("mode_of_collection", sa.String(), nullable=False),
        sa.Column("instrument_number", sa.String(), nullable=True),
        sa.Column(
            "instrument_amount", sa.Numeric(precision=15, scale=2), nullable=False
        ),
        sa.Column("date_of_instrument", sa.Date(), nullable=True),
        sa.Column("date_of_collection", sa.Date(), nullable=False),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["brs_details_id"],
            ["bank_recon_tieup_details.id"],
            name=op.f(
                "fk_bank_recon_tieup_outstanding_brs_details_id_bank_recon_tieup_details"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_recon_tieup_outstanding")),
    )
    op.create_table(
        "bank_recon_tieup_short_credit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("brs_details_id", sa.Integer(), nullable=False),
        sa.Column("mode_of_collection", sa.String(), nullable=False),
        sa.Column("instrument_number", sa.String(), nullable=True),
        sa.Column(
            "instrument_amount", sa.Numeric(precision=15, scale=2), nullable=False
        ),
        sa.Column("date_of_instrument", sa.Date(), nullable=True),
        sa.Column("date_of_collection", sa.Date(), nullable=False),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["brs_details_id"],
            ["bank_recon_tieup_details.id"],
            name=op.f(
                "fk_bank_recon_tieup_short_credit_brs_details_id_bank_recon_tieup_details"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_recon_tieup_short_credit")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bank_recon_tieup_short_credit")
    op.drop_table("bank_recon_tieup_outstanding")
    op.drop_table("bank_recon_tieup_excess_credit")
    op.drop_table("bank_recon_tieup_details")
    op.drop_table("bank_recon_tieup_summary")
    # ### end Alembic commands ###
