"""empty message

Revision ID: d6b0ac20e80b
Revises: b05919fda2ee
Create Date: 2025-11-20 10:45:22.732420

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d6b0ac20e80b"
down_revision = "b05919fda2ee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dqr_machines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ro_code", sa.String(), nullable=False),
        sa.Column("merchant_name", sa.String(), nullable=False),
        sa.Column("merchant_dba_name", sa.String(), nullable=False),
        sa.Column("mid", sa.String(), nullable=False),
        sa.Column("tid", sa.String(), nullable=False),
        sa.Column("mcc_code", sa.String(), nullable=False),
        sa.Column("office_code", sa.String(), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("pincode", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("login", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("device_name", sa.String(), nullable=False),
        sa.Column(
            "status", sa.Enum("Installed", "Pending", native_enum=False), nullable=True
        ),
        sa.Column("device_serial_number", sa.String(), nullable=False),
        sa.Column("installation_date", sa.Date(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dqr_machines")),
    )
    op.create_table(
        "dqr_refund",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organisation", sa.String(), nullable=False),
        sa.Column("ro_code", sa.String(), nullable=False),
        sa.Column("office_code", sa.String(), nullable=False),
        sa.Column("device_serial_number", sa.String(), nullable=False),
        sa.Column("refund_amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("txn_date", sa.Date(), nullable=False),
        sa.Column("txn_currency", sa.String(), nullable=False),
        sa.Column("refund_currency", sa.String(), nullable=False),
        sa.Column("auth_code", sa.String(), nullable=True),
        sa.Column("mid", sa.String(), nullable=False),
        sa.Column("tid", sa.String(), nullable=False),
        sa.Column("txn_amt", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("rrn", sa.String(), nullable=False),
        sa.Column("account_number", sa.String(), nullable=False),
        sa.Column("reason_for_refund", sa.Text(), nullable=False),
        sa.Column("refund_ref_no", sa.String(), nullable=True),
        sa.Column("refund_date", sa.Date(), nullable=True),
        sa.Column("ro_remarks", sa.Text(), nullable=True),
        sa.Column("refund_status", sa.String(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dqr_refund")),
    )
    with op.batch_alter_table("centralised_cheque_details", schema=None) as batch_op:
        batch_op.alter_column("summary_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column(
            "opening_balance_unencashed",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "cheques_issued",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "cheques_reissued_unencashed",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "opening_balance_stale",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "cheques_reissued_stale",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "cheques_cleared",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "cheques_cancelled",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "closing_balance_unencashed",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "closing_balance_stale",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column("remarks", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column(
            "prepared_by_employee_name", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "prepared_by_employee_number", existing_type=sa.VARCHAR(), nullable=False
        )

    with op.batch_alter_table(
        "centralised_cheque_enable_delete", schema=None
    ) as batch_op:
        batch_op.alter_column("date_of_month", existing_type=sa.DATE(), nullable=False)
        batch_op.alter_column(
            "enable_delete", existing_type=sa.BOOLEAN(), nullable=False
        )

    with op.batch_alter_table(
        "centralised_cheque_instrument_stale_details", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "voucher_number", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("voucher_date", existing_type=sa.DATE(), nullable=False)
        batch_op.alter_column(
            "transaction_id", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "instrument_number", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "instrument_date", existing_type=sa.DATE(), nullable=False
        )
        batch_op.alter_column(
            "instrument_amount",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column("payee_name", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("remarks", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column(
            "centralised_cheque_details_id", existing_type=sa.INTEGER(), nullable=False
        )

    with op.batch_alter_table(
        "centralised_cheque_instrument_unencashed_details", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "voucher_number", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("voucher_date", existing_type=sa.DATE(), nullable=False)
        batch_op.alter_column(
            "transaction_id", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "instrument_number", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "instrument_date", existing_type=sa.DATE(), nullable=False
        )
        batch_op.alter_column(
            "instrument_amount",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=False,
        )
        batch_op.alter_column("payee_name", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("remarks", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column(
            "centralised_cheque_details_id", existing_type=sa.INTEGER(), nullable=False
        )

    with op.batch_alter_table("centralised_cheque_summary", schema=None) as batch_op:
        batch_op.alter_column(
            "regional_office_code", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "operating_office_code", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column("date_of_month", existing_type=sa.DATE(), nullable=False)
        batch_op.alter_column(
            "centralised_cheque_bank", existing_type=sa.VARCHAR(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("centralised_cheque_summary", schema=None) as batch_op:
        batch_op.alter_column(
            "centralised_cheque_bank", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("date_of_month", existing_type=sa.DATE(), nullable=True)
        batch_op.alter_column(
            "operating_office_code", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "regional_office_code", existing_type=sa.VARCHAR(), nullable=True
        )

    with op.batch_alter_table(
        "centralised_cheque_instrument_unencashed_details", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "centralised_cheque_details_id", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column("remarks", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("payee_name", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "instrument_amount",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column("instrument_date", existing_type=sa.DATE(), nullable=True)
        batch_op.alter_column(
            "instrument_number", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "transaction_id", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("voucher_date", existing_type=sa.DATE(), nullable=True)
        batch_op.alter_column(
            "voucher_number", existing_type=sa.VARCHAR(), nullable=True
        )

    with op.batch_alter_table(
        "centralised_cheque_instrument_stale_details", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "centralised_cheque_details_id", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column("remarks", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("payee_name", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "instrument_amount",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column("instrument_date", existing_type=sa.DATE(), nullable=True)
        batch_op.alter_column(
            "instrument_number", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "transaction_id", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("voucher_date", existing_type=sa.DATE(), nullable=True)
        batch_op.alter_column(
            "voucher_number", existing_type=sa.VARCHAR(), nullable=True
        )

    with op.batch_alter_table(
        "centralised_cheque_enable_delete", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "enable_delete", existing_type=sa.BOOLEAN(), nullable=True
        )
        batch_op.alter_column("date_of_month", existing_type=sa.DATE(), nullable=True)

    with op.batch_alter_table("centralised_cheque_details", schema=None) as batch_op:
        batch_op.alter_column(
            "prepared_by_employee_number", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "prepared_by_employee_name", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column("remarks", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column(
            "closing_balance_stale",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "closing_balance_unencashed",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "cheques_cancelled",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "cheques_cleared",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "cheques_reissued_stale",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "opening_balance_stale",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "cheques_reissued_unencashed",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "cheques_issued",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "opening_balance_unencashed",
            existing_type=sa.NUMERIC(precision=15, scale=2),
            nullable=True,
        )
        batch_op.alter_column("summary_id", existing_type=sa.INTEGER(), nullable=True)

    op.drop_table("dqr_refund")
    op.drop_table("dqr_machines")
    # ### end Alembic commands ###
