"""empty message

Revision ID: d938996e7e62
Revises: 6fa3bd47d49e
Create Date: 2025-07-21 14:27:56.196815

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d938996e7e62"
down_revision = "6fa3bd47d49e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "escalation_matrix",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_type", sa.String(), nullable=True),
        sa.Column("nature_of_entity", sa.String(), nullable=True),
        sa.Column("name_of_entity", sa.String(), nullable=True),
        sa.Column("level", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("roll", sa.String(), nullable=True),
        sa.Column("email_address", sa.String(), nullable=True),
        sa.Column("contact_number", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_escalation_matrix")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("escalation_matrix")
    # ### end Alembic commands ###
