"""Create fund_signatory model

Revision ID: db840b3ff62f
Revises: 239eac26645e
Create Date: 2026-03-19 19:19:17.203448

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "db840b3ff62f"
down_revision = "239eac26645e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fund_signatory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("designation", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fund_signatory")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fund_signatory")
    # ### end Alembic commands ###
