"""empty message

Revision ID: dc60b74e8fe8
Revises: c1370e5faa5a
Create Date: 2025-09-09 11:05:55.416684

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dc60b74e8fe8"
down_revision = "c1370e5faa5a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fund_bank_statement", schema=None) as batch_op:
        batch_op.add_column(sa.Column("flag_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("batch_id", sa.UUID(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_fund_bank_statement_batch_id"), ["batch_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_fund_bank_statement_flag_id"), ["flag_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_fund_bank_statement_flag_id_fund_journal_voucher_flag_sheet"
            ),
            "fund_journal_voucher_flag_sheet",
            ["flag_id"],
            ["id"],
        )

    with op.batch_alter_table("pool_credits", schema=None) as batch_op:
        batch_op.add_column(sa.Column("batch_id", sa.UUID(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_pool_credits_batch_id"), ["batch_id"], unique=False
        )

    with op.batch_alter_table("pool_credits_portal", schema=None) as batch_op:
        batch_op.add_column(sa.Column("batch_id", sa.UUID(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_pool_credits_portal_batch_id"), ["batch_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pool_credits_portal", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pool_credits_portal_batch_id"))
        batch_op.drop_column("batch_id")

    with op.batch_alter_table("pool_credits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pool_credits_batch_id"))
        batch_op.drop_column("batch_id")

    with op.batch_alter_table("fund_bank_statement", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f(
                "fk_fund_bank_statement_flag_id_fund_journal_voucher_flag_sheet"
            ),
            type_="foreignkey",
        )
        batch_op.drop_index(batch_op.f("ix_fund_bank_statement_flag_id"))
        batch_op.drop_index(batch_op.f("ix_fund_bank_statement_batch_id"))
        batch_op.drop_column("batch_id")
        batch_op.drop_column("flag_id")

    # ### end Alembic commands ###
