"""empty message

Revision ID: f62231c3621f
Revises: 63040ebc6aba
Create Date: 2025-03-25 11:22:15.658880

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f62231c3621f"
down_revision = "63040ebc6aba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coinsurance_token_request_id",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hub_office_code", sa.String(), nullable=True),
        sa.Column("company_name", sa.String(), nullable=True),
        sa.Column("coinsurer_office_code", sa.String(), nullable=True),
        sa.Column("name_of_insured", sa.String(), nullable=True),
        sa.Column("request_id", sa.String(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("type_of_amount", sa.String(), nullable=True),
        sa.Column("gl_code", sa.String(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("upload_document", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coinsurance_token_request_id")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("coinsurance_token_request_id")
    # ### end Alembic commands ###
