"""Fund intimation: Create models

Revision ID: f9db1e718c2e
Revises: 5ae9796ab282
Create Date: 2026-09-29 22:35:01.881780

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f9db1e718c2e"
down_revision = "5ae9796ab282"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fund_intimation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("regional_office_code", sa.String(), nullable=False),
        sa.Column("operating_office_code", sa.String(), nullable=False),
        sa.Column("type_of_disbursement", sa.String(), nullable=False),
        sa.Column("nature_of_recipient", sa.String(), nullable=False),
        sa.Column("name_of_recipient", sa.String(), nullable=False),
        sa.Column("purpose_of_disbursement", sa.String(), nullable=False),
        sa.Column("claim_number", sa.String(), nullable=True),
        sa.Column("coinsurance_involved", sa.Boolean(), nullable=True),
        sa.Column("coinsurance_details", sa.Text(), nullable=True),
        sa.Column("date_of_intimation", sa.Date(), nullable=False),
        sa.Column("transaction_id", sa.String(), nullable=True),
        sa.Column("transaction_date", sa.Date(), nullable=True),
        sa.Column(
            "transaction_amount", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column("expected_date_of_disbursement", sa.Date(), nullable=True),
        sa.Column("regional_office_remarks", sa.Text(), nullable=True),
        sa.Column("head_office_remarks", sa.Text(), nullable=True),
        sa.Column("utr_number", sa.String(), nullable=True),
        sa.Column("utr_date", sa.Date(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fund_intimation")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fund_intimation")
    # ### end Alembic commands ###
