"""Audit certificate: Add new columns in models

Revision ID: fc0ba4b66f7f
Revises: 9ff332adc359
Create Date: 2026-05-21 21:06:19.403565

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fc0ba4b66f7f"
down_revision = "9ff332adc359"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("auditor_certificate", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tender_number", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("invoice_number", sa.String(), nullable=True))
        batch_op.create_unique_constraint(
            batch_op.f("uq_auditor_certificate_invoice_number"), ["invoice_number"]
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_auditor_certificate_tender_number"), ["tender_number"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("auditor_certificate", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_auditor_certificate_tender_number"), type_="unique"
        )
        batch_op.drop_constraint(
            batch_op.f("uq_auditor_certificate_invoice_number"), type_="unique"
        )
        batch_op.drop_column("invoice_number")
        batch_op.drop_column("tender_number")

    # ### end Alembic commands ###
